//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ERP.Utility;
using System;


namespace ERP.Data.GraphModel
{

    public partial class SPS_SuccessionPlanning : NodeBase
    {
        public DateTime? ClosedDate { get; set; }
        public SuccessionPlanningStatusEnum? DocumentStatus { get; set; }
    }  
    
    public class R_SuccessionPlanning_SuccessionPlanningMaster : RelationshipBase
    {

    }
    public class R_SuccessionPlanning_DocumentOwner_User : RelationshipBase
    {

    }    
   
}
