//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.UI.Web.Resources.Areas.CHR.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserHierarchyController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserHierarchyController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMS.UI.Web.Resources.Areas.CHR.Controllers.UserHierarchyController", typeof(UserHierarchyController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin User Name.
        /// </summary>
        public static string AdminUserName {
            get {
                return ResourceManager.GetString("AdminUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee No.
        /// </summary>
        public static string EmployeeNo {
            get {
                return ResourceManager.GetString("EmployeeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarchy.
        /// </summary>
        public static string Hierarchy {
            get {
                return ResourceManager.GetString("Hierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Name.
        /// </summary>
        public static string JobName {
            get {
                return ResourceManager.GetString("JobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Name.
        /// </summary>
        public static string OrganizationName {
            get {
                return ResourceManager.GetString("OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select atleast one user from the grid.
        /// </summary>
        public static string PleaseSelectatleastoneuserfromthegrid {
            get {
                return ResourceManager.GetString("PleaseSelectatleastoneuserfromthegrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select The Hierarchy Name.
        /// </summary>
        public static string PleaseSelectTheHierarchyName {
            get {
                return ResourceManager.GetString("PleaseSelectTheHierarchyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor Name.
        /// </summary>
        public static string Sponsor_Name {
            get {
                return ResourceManager.GetString("Sponsor Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsorship No.
        /// </summary>
        public static string SponsorshipNo {
            get {
                return ResourceManager.GetString("SponsorshipNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Hierarchy.
        /// </summary>
        public static string UpdateHierarchy {
            get {
                return ResourceManager.GetString("UpdateHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Hierarchy Level.
        /// </summary>
        public static string UpdateHierarchyLevel {
            get {
                return ResourceManager.GetString("UpdateHierarchyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Hierarchy.
        /// </summary>
        public static string UserHierarchy {
            get {
                return ResourceManager.GetString("UserHierarchy", resourceCulture);
            }
        }
    }
}
