//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Translation.Sps {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SuccessionPlanning {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SuccessionPlanning() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERP.Translation.Sps.SuccessionPlanning", typeof(SuccessionPlanning).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Type.
        /// </summary>
        public static string AccessType {
            get {
                return ResourceManager.GetString("AccessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string base64Img {
            get {
                return ResourceManager.GetString("base64Img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Date.
        /// </summary>
        public static string ClosedDate {
            get {
                return ResourceManager.GetString("ClosedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Stage Id.
        /// </summary>
        public static string CurrentStageId {
            get {
                return ResourceManager.GetString("CurrentStageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Service Template Master Id.
        /// </summary>
        public static string CycleServiceTemplateMasterId {
            get {
                return ResourceManager.GetString("CycleServiceTemplateMasterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development Plan.
        /// </summary>
        public static string DevelopmentPlan {
            get {
                return ResourceManager.GetString("DevelopmentPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development Service Template Master Id.
        /// </summary>
        public static string DevelopmentServiceTemplateMasterId {
            get {
                return ResourceManager.GetString("DevelopmentServiceTemplateMasterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Owner User Id.
        /// </summary>
        public static string DocumentOwnerUserId {
            get {
                return ResourceManager.GetString("DocumentOwnerUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Status.
        /// </summary>
        public static string DocumentStatus {
            get {
                return ResourceManager.GetString("DocumentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Succession Cycle.
        /// </summary>
        public static string DownloadSuccessionCycle {
            get {
                return ResourceManager.GetString("DownloadSuccessionCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus Service Id.
        /// </summary>
        public static string FocusServiceId {
            get {
                return ResourceManager.GetString("FocusServiceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succession Planning.
        /// </summary>
        public static string HeaderTitle {
            get {
                return ResourceManager.GetString("HeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Succession Planning Summary.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succession Planning Summary -.
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Manager.
        /// </summary>
        public static string LineManager {
            get {
                return ResourceManager.GetString("LineManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Manager Job Title.
        /// </summary>
        public static string LineManagerJobTitle {
            get {
                return ResourceManager.GetString("LineManagerJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Manager User Id.
        /// </summary>
        public static string LineManagerUserId {
            get {
                return ResourceManager.GetString("LineManagerUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Succession Planning.
        /// </summary>
        public static string LnkManageSP {
            get {
                return ResourceManager.GetString("LnkManageSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succession Planning DashBoard.
        /// </summary>
        public static string LnkSPDashboard {
            get {
                return ResourceManager.GetString("LnkSPDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succession Planning Mater.
        /// </summary>
        public static string LnkSPMaster {
            get {
                return ResourceManager.GetString("LnkSPMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Development Plan.
        /// </summary>
        public static string PrintDevelopmentReport {
            get {
                return ResourceManager.GetString("PrintDevelopmentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Id.
        /// </summary>
        public static string ServiceId {
            get {
                return ResourceManager.GetString("ServiceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succession Cycle.
        /// </summary>
        public static string SuccessionCycle {
            get {
                return ResourceManager.GetString("SuccessionCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succession Planning Id.
        /// </summary>
        public static string SuccessionPlanningId {
            get {
                return ResourceManager.GetString("SuccessionPlanningId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succession Planning Master Id.
        /// </summary>
        public static string SuccessionPlanningMasterId {
            get {
                return ResourceManager.GetString("SuccessionPlanningMasterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successions.
        /// </summary>
        public static string successions {
            get {
                return ResourceManager.GetString("successions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Status.
        /// </summary>
        public static string ViewStatus {
            get {
                return ResourceManager.GetString("ViewStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
