//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Translation.Sps {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SuccessionPlanningService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SuccessionPlanningService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERP.Translation.Sps.SuccessionPlanningService", typeof(SuccessionPlanningService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Cycles.
        /// </summary>
        public static string AddCycles {
            get {
                return ResourceManager.GetString("AddCycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Development Plan.
        /// </summary>
        public static string AddDevelopmentPlan {
            get {
                return ResourceManager.GetString("AddDevelopmentPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion Date.
        /// </summary>
        public static string CompletionDate {
            get {
                return ResourceManager.GetString("CompletionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Name.
        /// </summary>
        public static string CycleName {
            get {
                return ResourceManager.GetString("CycleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle No.
        /// </summary>
        public static string CycleNo {
            get {
                return ResourceManager.GetString("CycleNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Status.
        /// </summary>
        public static string CycleStatus {
            get {
                return ResourceManager.GetString("CycleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the Development?.
        /// </summary>
        public static string DeleteDevMsg {
            get {
                return ResourceManager.GetString("DeleteDevMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the Goal?.
        /// </summary>
        public static string DeleteGoalMsg {
            get {
                return ResourceManager.GetString("DeleteGoalMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development Plan.
        /// </summary>
        public static string DevelopmentPlan {
            get {
                return ResourceManager.GetString("DevelopmentPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development Status.
        /// </summary>
        public static string DevelopmentStatus {
            get {
                return ResourceManager.GetString("DevelopmentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsConfidential.
        /// </summary>
        public static string IsConfidential {
            get {
                return ResourceManager.GetString("IsConfidential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner User Id.
        /// </summary>
        public static string OwnerUserId {
            get {
                return ResourceManager.GetString("OwnerUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PmsAccessType.
        /// </summary>
        public static string PmsAccessType {
            get {
                return ResourceManager.GetString("PmsAccessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PositionId.
        /// </summary>
        public static string PositionId {
            get {
                return ResourceManager.GetString("PositionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferenceTypeCode.
        /// </summary>
        public static string ReferenceTypeCode {
            get {
                return ResourceManager.GetString("ReferenceTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestaurantIds.
        /// </summary>
        public static string RestaurantIds {
            get {
                return ResourceManager.GetString("RestaurantIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Restaurants....
        /// </summary>
        public static string SelectResturantsPlaceholder {
            get {
                return ResourceManager.GetString("SelectResturantsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Id.
        /// </summary>
        public static string ServiceId {
            get {
                return ResourceManager.GetString("ServiceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name.
        /// </summary>
        public static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service No.
        /// </summary>
        public static string ServiceNo {
            get {
                return ResourceManager.GetString("ServiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Status Code.
        /// </summary>
        public static string ServiceStatusCode {
            get {
                return ResourceManager.GetString("ServiceStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Status Name.
        /// </summary>
        public static string ServiceStatusName {
            get {
                return ResourceManager.GetString("ServiceStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Template Master Id.
        /// </summary>
        public static string ServiceTemplateMasterId {
            get {
                return ResourceManager.GetString("ServiceTemplateMasterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLA(In Days).
        /// </summary>
        public static string SLA {
            get {
                return ResourceManager.GetString("SLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date Display.
        /// </summary>
        public static string StartDateDisplay {
            get {
                return ResourceManager.GetString("StartDateDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succession Planning Id.
        /// </summary>
        public static string SuccessionPlanningId {
            get {
                return ResourceManager.GetString("SuccessionPlanningId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary By Restaurants.
        /// </summary>
        public static string SummaryByRestaurants {
            get {
                return ResourceManager.GetString("SummaryByRestaurants", resourceCulture);
            }
        }
    }
}
