//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.UI.Web.Resources.Areas.CHR.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PayrollSlipController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PayrollSlipController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMS.UI.Web.Resources.Areas.CHR.Controllers.PayrollSlipController", typeof(PayrollSlipController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee No.
        /// </summary>
        public static string EmployeeNo {
            get {
                return ResourceManager.GetString("EmployeeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iqamah No.
        /// </summary>
        public static string IqamahNo {
            get {
                return ResourceManager.GetString("IqamahNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Amount.
        /// </summary>
        public static string NetAmount {
            get {
                return ResourceManager.GetString("NetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll End Date.
        /// </summary>
        public static string PayrollEndDate {
            get {
                return ResourceManager.GetString("PayrollEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll Slip.
        /// </summary>
        public static string PayrollSlip {
            get {
                return ResourceManager.GetString("PayrollSlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll StartDate.
        /// </summary>
        public static string PayrollStartDate {
            get {
                return ResourceManager.GetString("PayrollStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Name.
        /// </summary>
        public static string SalaryName {
            get {
                return ResourceManager.GetString("SalaryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Deduction.
        /// </summary>
        public static string TotalDeduction {
            get {
                return ResourceManager.GetString("TotalDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Earning.
        /// </summary>
        public static string TotalEarning {
            get {
                return ResourceManager.GetString("TotalEarning", resourceCulture);
            }
        }
    }
}
