version: '3'
services:
  nginx:
    image: nginx:alpine
    hostname: 'nginx'
    container_name: 'nginxweb'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - /var/wellknown:/var/tmp/:ro
#     Only For SSL Implementation
      - ./nginx/upcctns/bundle.crt:/etc/nginx/ssl/bundle.crt:ro
      - ./nginx/upcctns/bundle.key:/etc/nginx/ssl/bundle.key:ro
#      - ./nginx/logs/:/var/log/nginx/
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - api
    restart: always

  api:
    image: dockerhub.aitalkx.com:5001/cmswebmap:latest
    ports:
      - '5000'
    restart: always


networks:
  default:
    external:
      name: cmssynergy_default