using Synergy.App.DataModel;
using Synergy.App.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Synergy.App.Business
{
    public interface ITalentAssessmentQueryBusiness : IBusinessBase<NoteViewModel, NtsNote>
    {
        Task<List<SurveyQuestionViewModel>> GetHRUserSurveyData();
        Task<List<SurveyTopicViewModel>> GetQuestionsForSurveyResult(string surveyId);
        Task<SurveyTopicViewModel> CheckIfSurveyAnswerResultExist(string questionId, string surveyResultId);
        Task<ServiceTemplateViewModel> GetSurveyResultDetails(string surveyId, string surveyScheduleUserId, string surveyUserId);
        Task<ServiceTemplateViewModel> CheckSurveyResultExist(string surveyScheduleUserId);
        Task<List<SurveyQuestionViewModel>> GetSurveyResult(string surveyResultId, string lang);
        Task<List<ServiceTemplateViewModel>> GetSurveyScheduleUser(string SurveyScheduleId, string UserId);
        Task UpdateScheduleSurveyUserExpiryDate(string surveyScheduleId, string expiryDate);
        Task<SurveyScheduleViewModel> GetSurveyCode(int surveyCode);
        Task<List<SurveyScheduleViewModel>> GetSurveyScheduleDetailsById(string surveyId, string surveyScheduleId);
        Task<List<SurveyScheduleViewModel>> GetSurveyDetail(string id);
        Task<SurveyScheduleViewModel> GetSurveyScheduleById(string surveyId);
        Task<List<SurveyScheduleViewModel>> GetSurveyScheduleList(string surveyId, string status);
        Task<SurveyScheduleViewModel> GetSurveyScheduleDetails(string surveyScheduleId);
        Task<List<AssessmentQuestionsOptionViewModel>> GetSurveyOptions(string noteId, string serviceId, string lang, string assessmentId, string surveyScheduleUserId);
        Task<List<AssessmentDetailViewModel>> GetAssessmentData(string serviceId, string lang);
        Task UpdatePreferredLanguage(string surveyScheduleId, string lang, string surveyResultId);
        Task<AssessmentDetailViewModel> GetSurveyAssessmentQuestion(string serviceId);
        Task<AssessmentViewModel> GetAssessmentReportByUserId(string userId, string masterCode);
        Task<AssessmentDetailViewModel> GetInterviewAssessmentReportByUserId(string userId);
        Task<AssessmentResultViewModel> GetManageAssessmentResult(string userId);
        Task<List<AssessmentResultViewModel>> GetManageAssessmentResultList(string userId);
        Task<List<AssessmentViewModel>> GetAssessmentSetList();
        Task<List<AssessmentViewModel>> GetAssessmentSetAssessmentList(string AssessmentSetId);
        Task DeleteAssessmentSet(string NoteId);
        Task DeleteAssessmentSetAsessment(string NoteId);
        Task<List<IdNameViewModel>> GetAssessmentListToSet(string TypeId);
        Task<AssessmentViewModel> GetAssessmentSetAssessmentByid(string NoteId);
        Task<IdNameViewModel> GetSquenceNoExistAssessmentSet(string AssessmentSetId, string SequenceNo);
        Task<IdNameViewModel> GetAssessmentExistAssessmentSet(string AssessmentSetId, string AssessmentId, string Id);
        Task<List<AssessmentInterviewViewModel>> GetAssessmentReportMinistryList(string SponsorId = null, string userId = null);
        Task<IdNameViewModel> GetSponsorDetailsByUserId(string UserId);
        Task<List<AssessmentDetailViewModel>> GetAssessmentListByUserId(string userId, string statusCode, string typeId);
        Task<string> GetUserIdentificationByUserId(string userId);
        Task<List<AssessmentInterviewViewModel>> GetInterviewList(string UserID, string status);
        Task<IdNameViewModel> GetIndicatorbyName(string Name);
        Task<IdNameViewModel> GetCompetencybyName(string Name);
        Task<IdNameViewModel> GetAssessmentbyName(string Name);
        Task<SurveyScheduleViewModel> GetSurveyDetails(string surveyScheduleUserId, string surveyCode = null);
        Task DeleteAssessmentSchedule(string id);
        Task<List<AssessmentDetailViewModel>> GetAssessmentQuistionNaireResultByUser(string UserID);
        Task<AssessmentDetailViewModel> GetAssessmentCaseStudyResultByUser(string UserID);
        Task<bool> UpdateUserResult(string Id, string Scores);
        Task<bool> UpdateInterViewScore(string Id, string Scores, string ActualStartDate, string ActualEndDate);
        Task<IdNameViewModel> GetCanidateId(string UserId);
        Task<bool> UpdateAssessmentArchived(string serviceIds, bool archive = false);
        Task<IdNameViewModel> Getinterviewid(string ServiceId);
        Task<List<AssessmentCalendarViewModel>> GetCalendarScheduleList(string loggedInUserId = null, string role = null);
        Task<AssessmentCalendarViewModel> GetCalendarScheduleById(string id);
        Task<List<EmailViewModel>> GetSlotUserEmail(string slotId);
        Task<EmailViewModel> GetEmailById(string emailId);
        Task ChangeUserProfilePhoto(string photoId, string userId);
        Task<AssessmentInterviewViewModel> GetserviceScore(string ServiceID);
        Task<List<InterViewQuestionViewModel>> GetInterviewAssessmentQuestions(string userId, string Tableid);
        Task<List<AssessmentQuestionsOptionViewModel>> GetOptionList(string QuestionId);
        Task<List<AssessmentAnswerViewModel>> GetQuestionOptionList(string AssesmentId, string UserId);
        Task<List<AssessmentDetailViewModel>> GetAssessmentReporTechnical(string UserID);
        Task<AssessmentDetailViewModel> GetAssessmentReport(string UserID);
        Task<List<InterViewQuestionViewModel>> GetRandamQuestions();
        Task<List<InterViewQuestionViewModel>> GetQuestionDetails(string UserId, string TableId);
        Task<List<InterViewQuestionViewModel>> GetQuestionListofUser(string UserId, string TableId);
        Task<AssessmentInterviewViewModel> GetInterviewService(string UserID);
        Task<List<IdNameViewModel>> GetInterviewAssessorList(string UserId);
        Task UpdateCandidateId(string userId, string fileId, string type);
        Task<List<AssessmentInterviewViewModel>> GetAssessmentInterview(string UserID, bool isarchived = false, string source = null);
        Task ManageAssessmentStatus(bool isAssessmentStopped, ServiceViewModel sermodel);
        Task UpdateSurvey(ServiceTemplateViewModel service, string nextQTopicId = null);
        Task UpdateAssessment(ServiceTemplateViewModel service, int? timeElapsed, int? timeElapsedSec, string nextQuestionId = null, DateTime? startDate = null);
        Task<bool> GetAssessmentStatus(string serviceId);
        Task<AssessmentAnswerViewModel> GetAssessmentAnswer(string serviceId, string currentQuestionId);
        Task<AssessmentResultViewModel> GetAssessmentResult(ServiceTemplateViewModel service1);
        Task UpdateAssessmentResult(ServiceTemplateViewModel service1);
        Task<List<AssessmentQuestionsOptionViewModel>> GetOptions(string noteId, string serviceId, string lang, string assessmentId);
        Task UpdateScoreComment(List<AssessmentAnswerViewModel> modelList);
        Task<AssessmentAnswerViewModel> GetQuestionByAnswerId(string noteId);
        Task<List<AssessmentDetailViewModel>> GetAssessmentQuestionsDetail(string serviceId, string lang);
        Task<AssessmentDetailViewModel> GetAssessmentQuestionArabic(string serviceId);
        Task<AssessmentDetailViewModel> GetAssessmentQuestionEnglish(string serviceId);
        Task<List<AssessmentQuestionsOptionViewModel>> GetTryoutQuestionOptions(string noteId, string lang);
        Task<List<AssessmentDetailViewModel>> GetQuestions(string assessmentId, string lang);
        Task<IList<TeamWorkloadViewModel>> ReadPerformanceTaskViewData(string projectId);
        Task<IList<TeamWorkloadViewModel>> ReadPerformanceDevelopmentViewData();
        Task<IList<IdNameViewModel>> GetCompetencyList();
        Task<List<AssignmentViewModel>> ReadCertificationData(string userId);
        Task<List<AssignmentViewModel>> ReadSkillData(string userId);
        Task<List<AssessmentDetailViewModel>> GetAssessmentListByUserId(string userId, string statusCode);
        Task<List<AssessmentDetailViewModel>> GetCompletedAssessmentListByUserId(string userId);
        Task<List<IdNameViewModel>> GetAssessmentSetListIdName();
        Task<List<IdNameViewModel>> GetAssessmentListIdName(string assSetId);
        Task<List<IdNameViewModel>> GetAssessmentProctorList();
        Task<IList<IdNameViewModel>> GetIndicatorList(string levelId = null);
        Task<IList<IdNameViewModel>> GetCompetencyLevelList(string noteId = null);
        Task<SurveyScheduleViewModel> GetSurveyClosingInstruction(string surveyId);
        Task<SurveyTopicViewModel> GetSurveyQuestion(string serviceId);
        Task<AssessmentResultViewModel> GetQuestion(string serviceId);
        Task<List<AssessmentDetailViewModel>> GetAllAssessmentsList();
        Task<List<IdNameViewModel>> GetJobTitle(string loggedInUserId);
        Task<IdNameViewModel> GetQuestionCountByTopic(string topicId);
        Task<IList<IdNameViewModel>> GetCompetencyLevelListByTopic(string topicId);
        Task DeleteAssessmentQuestion(string NoteId);
        Task<List<AssessmentQuestionsViewModel>> GetMappedQuestionsList(string assessmentId);
        Task UpdateSequenceNo(string Id, long? sequenceNo);
        Task<List<AssessmentQuestionsViewModel>> GetAllQuestions(string assessmentTypeId);
        Task<List<IdNameViewModel>> GetJobTitles(string departmentId);
        Task<List<CapacityRiskViewModel>> GetJobCapacityChartData(string jobids, string jobId);
        Task<List<CapacityRiskViewModel>> GetJobCapacityChartData(string jobId);
        Task<AssignmentViewModel> GetAssignmentDetails(string userId);
        Task<List<AssignmentViewModel>> ReadBadgeData(string userId);
        Task<List<AssignmentViewModel>> ReadAssessmentData(string userId);
        Task<List<CapacityRiskViewModel>> GetJobCapacityData(string deptids);
        Task<List<AssessmentViewModel>> GetQuestionsByAssessmentId(string assessmentId);
        Task<List<AssessmentQuestionsOptionViewModel>> GetOptionsForQuestion(string questionNoteId);
        Task<List<AssessmentQuestionsOptionViewModel>> GetOptionsByQuestionId(string questionId);
        Task<List<AssessmentQuestionsViewModel>> GetQuestion();
        Task<List<AssessmentQuestionsViewModel>> GetTreeListQuestion();
        Task<IList<AssessmentQuestionsViewModel>> GetAssessmentQuestions(string topic, string level);
        Task<AssessmentQuestionsOptionViewModel> GetOptionsById(string Id);
        Task DeleteOption(string id);
        Task<List<AssessmentViewModel>> GetAssessmentsList(string type, string searchtext);
        Task DeleteAssessment(string NoteId);
        Task<AssessmentViewModel> GetAssessmentDetailsById(string assmntId);

        Task UpdateSurveyResultAnswer(SurveyTopicViewModel model);

        Task<SurveyScheduleViewModel> AssignDummySurveyToUser(string surveyScheduleId, string surveyUserId);

        Task<long> GetSurveyUserCount(string prefix);
    }
}
