//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Data.Model
{
    using System;
    using System.Collections.Generic;

    public partial class ADM_Block : AdminBase
    {
        public string Name { get; set; }
        public ulong TabId { get; set; }
        public ulong BlockId { get; set; }
        public ICollection<ADM_Action> Actions { get; set; }
        public ICollection<ADM_Field> Fields { get; set; }
        public ICollection<ADM_FieldEditable> FieldEditable { get; set; }

    }
}
