//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ERP.Utility;
using System;

namespace ERP.Data.GraphModel
{
    public partial class ADM_WebinarRegistration : NodeBase
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Organization { get; set; }
        public string Designation { get; set; }
        public bool CanAttend { get; set; }   
    }
    public class R_WebinarRegistration_Country : RelationshipBase
    {

    }
    public class R_WebinarRegistration_Webinar : RelationshipBase
    {

    }
}
