//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Data.GraphModel
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

  
    public partial class ADM_Screen : NodeBase
    {  
        public string Name { get; set; } 
    }
    public class R_Screen_SubModule : RelationshipBase
    {

    }
}
