//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.UI.Web.Resources.Areas.TAA.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AttendanceController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AttendanceController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMS.UI.Web.Resources.Areas.TAA.Controllers.AttendanceController", typeof(AttendanceController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Log Text.
        /// </summary>
        public static string AccessLogText {
            get {
                return ResourceManager.GetString("AccessLogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual.
        /// </summary>
        public static string Actual {
            get {
                return ResourceManager.GetString("Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual(Sign In - Sign Out).
        /// </summary>
        public static string Actual_SignIn_SignOut_ {
            get {
                return ResourceManager.GetString("Actual(SignIn-SignOut)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Hours.
        /// </summary>
        public static string ActualHours {
            get {
                return ResourceManager.GetString("ActualHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActualText.
        /// </summary>
        public static string ActualText {
            get {
                return ResourceManager.GetString("ActualText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual &lt;br/&gt;(Time In - Time Out).
        /// </summary>
        public static string Actualtimeintimeout {
            get {
                return ResourceManager.GetString("Actualtimeintimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Att Date.
        /// </summary>
        public static string AttDate {
            get {
                return ResourceManager.GetString("AttDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        public static string Attendance {
            get {
                return ResourceManager.GetString("Attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance Status.
        /// </summary>
        public static string AttendanceStatus {
            get {
                return ResourceManager.GetString("AttendanceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated.
        /// </summary>
        public static string Calculated {
            get {
                return ResourceManager.GetString("Calculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Roster.
        /// </summary>
        public static string CreateRoster {
            get {
                return ResourceManager.GetString("CreateRoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeductionHours.
        /// </summary>
        public static string DeductionHours {
            get {
                return ResourceManager.GetString("DeductionHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Comment.
        /// </summary>
        public static string EmployeeComment {
            get {
                return ResourceManager.GetString("EmployeeComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Comments.
        /// </summary>
        public static string EmployeeComments {
            get {
                return ResourceManager.GetString("EmployeeComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee No.
        /// </summary>
        public static string EmployeeNo {
            get {
                return ResourceManager.GetString("EmployeeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Status.
        /// </summary>
        public static string EmployeeStatus {
            get {
                return ResourceManager.GetString("EmployeeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To Excel.
        /// </summary>
        public static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string Fromdate {
            get {
                return ResourceManager.GetString("Fromdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Name.
        /// </summary>
        public static string JobName {
            get {
                return ResourceManager.GetString("JobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Name.
        /// </summary>
        public static string OrganizationName {
            get {
                return ResourceManager.GetString("OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTHours.
        /// </summary>
        public static string OTHours {
            get {
                return ResourceManager.GetString("OTHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override.
        /// </summary>
        public static string Override {
            get {
                return ResourceManager.GetString("Override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override Attendance.
        /// </summary>
        public static string OverrideAttendance {
            get {
                return ResourceManager.GetString("OverrideAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override Comments.
        /// </summary>
        public static string OverrideComment {
            get {
                return ResourceManager.GetString("OverrideComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override Comments.
        /// </summary>
        public static string OverrideComments {
            get {
                return ResourceManager.GetString("OverrideComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OverrideDeductionHoursText.
        /// </summary>
        public static string OverrideDeductionHoursText {
            get {
                return ResourceManager.GetString("OverrideDeductionHoursText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override OT Hours Text.
        /// </summary>
        public static string OverrideOTHoursText {
            get {
                return ResourceManager.GetString("OverrideOTHoursText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override OT Service.
        /// </summary>
        public static string OverrideOTService {
            get {
                return ResourceManager.GetString("OverrideOTService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over Time Hours.
        /// </summary>
        public static string OverTimeHours {
            get {
                return ResourceManager.GetString("OverTimeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll Group.
        /// </summary>
        public static string PayrollGroup {
            get {
                return ResourceManager.GetString("PayrollGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period From.
        /// </summary>
        public static string PeriodFrom {
            get {
                return ResourceManager.GetString("PeriodFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permitted.
        /// </summary>
        public static string Permitted {
            get {
                return ResourceManager.GetString("Permitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostedForPayroll.
        /// </summary>
        public static string PostedForPayroll {
            get {
                return ResourceManager.GetString("PostedForPayroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roster.
        /// </summary>
        public static string Roster {
            get {
                return ResourceManager.GetString("Roster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roster(Sign In - Sign Out).
        /// </summary>
        public static string Roster_SignIn_SignOut_ {
            get {
                return ResourceManager.GetString("Roster(SignIn-SignOut)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roster Hours.
        /// </summary>
        public static string RosterHours {
            get {
                return ResourceManager.GetString("RosterHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roster Text.
        /// </summary>
        public static string RosterText {
            get {
                return ResourceManager.GetString("RosterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string s {
            get {
                return ResourceManager.GetString("s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Month.
        /// </summary>
        public static string SearchMonth {
            get {
                return ResourceManager.GetString("SearchMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Time Hours.
        /// </summary>
        public static string ShortTimeHours {
            get {
                return ResourceManager.GetString("ShortTimeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit For Payroll.
        /// </summary>
        public static string SubmitForPayroll {
            get {
                return ResourceManager.GetString("SubmitForPayroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Attendance.
        /// </summary>
        public static string SystemAttendance {
            get {
                return ResourceManager.GetString("SystemAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Deduction Hours Text.
        /// </summary>
        public static string SystemDeductionHoursText {
            get {
                return ResourceManager.GetString("SystemDeductionHoursText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System OT Hours Text.
        /// </summary>
        public static string SystemOTHoursText {
            get {
                return ResourceManager.GetString("SystemOTHoursText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roster &lt;br/&gt;(Time In - Time Out).
        /// </summary>
        public static string Timeintimeout {
            get {
                return ResourceManager.GetString("Timeintimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Permission Request.
        /// </summary>
        public static string TimePermissionRequest {
            get {
                return ResourceManager.GetString("TimePermissionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string Todate {
            get {
                return ResourceManager.GetString("Todate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Absent.
        /// </summary>
        public static string TotalAbsent {
            get {
                return ResourceManager.GetString("TotalAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total DED.
        /// </summary>
        public static string TotalDED {
            get {
                return ResourceManager.GetString("TotalDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total OT.
        /// </summary>
        public static string TotalOT {
            get {
                return ResourceManager.GetString("TotalOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Present.
        /// </summary>
        public static string TotalPresent {
            get {
                return ResourceManager.GetString("TotalPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Attendance.
        /// </summary>
        public static string UpdateAttendance {
            get {
                return ResourceManager.GetString("UpdateAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
