//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Translation.Nts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Field {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Field() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERP.Translation.Nts.Field", typeof(Field).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Info.
        /// </summary>
        public static string AdditionalInfo {
            get {
                return ResourceManager.GetString("AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field corrected Successfully.
        /// </summary>
        public static string AlertCorrectSuccess {
            get {
                return ResourceManager.GetString("AlertCorrectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Field created Successfully.
        /// </summary>
        public static string AlertCreateSuccess {
            get {
                return ResourceManager.GetString("AlertCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field deleted Successfully.
        /// </summary>
        public static string AlertDeleteSuccess {
            get {
                return ResourceManager.GetString("AlertDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field updated Successfully.
        /// </summary>
        public static string AlertUpdateSuccess {
            get {
                return ResourceManager.GetString("AlertUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Name.
        /// </summary>
        public static string AreaName {
            get {
                return ResourceManager.GetString("AreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Bind.
        /// </summary>
        public static string AutoBind {
            get {
                return ResourceManager.GetString("AutoBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Maximum Length.
        /// </summary>
        public static string CharacterMaximumLength {
            get {
                return ResourceManager.GetString("CharacterMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Minimum Length.
        /// </summary>
        public static string CharacterMinimumLength {
            get {
                return ResourceManager.GetString("CharacterMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client DataBind Script.
        /// </summary>
        public static string ClientDataBindScript {
            get {
                return ResourceManager.GetString("ClientDataBindScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client OnChange Script.
        /// </summary>
        public static string ClientOnChangeScript {
            get {
                return ResourceManager.GetString("ClientOnChangeScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ReadOnly Script.
        /// </summary>
        public static string ClientReadOnlyScript {
            get {
                return ResourceManager.GetString("ClientReadOnlyScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Validation Script.
        /// </summary>
        public static string ClientValidationScript {
            get {
                return ResourceManager.GetString("ClientValidationScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Visibility Script.
        /// </summary>
        public static string ClientVisibilityScript {
            get {
                return ResourceManager.GetString("ClientVisibilityScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Field.
        /// </summary>
        public static string CreateField {
            get {
                return ResourceManager.GetString("CreateField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Format String.
        /// </summary>
        public static string DataFormatString {
            get {
                return ResourceManager.GetString("DataFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Length.
        /// </summary>
        public static string DataLength {
            get {
                return ResourceManager.GetString("DataLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSource Action Name.
        /// </summary>
        public static string DataSourceActionName {
            get {
                return ResourceManager.GetString("DataSourceActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSource Area Name.
        /// </summary>
        public static string DataSourceAreaName {
            get {
                return ResourceManager.GetString("DataSourceAreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSource Controller Name.
        /// </summary>
        public static string DataSourceControllerName {
            get {
                return ResourceManager.GetString("DataSourceControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSource HtmlAttributes.
        /// </summary>
        public static string DataSourceHtmlAttributesString {
            get {
                return ResourceManager.GetString("DataSourceHtmlAttributesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSource Parameters.
        /// </summary>
        public static string DataSourceParameters {
            get {
                return ResourceManager.GetString("DataSourceParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Text Field.
        /// </summary>
        public static string DataTextField {
            get {
                return ResourceManager.GetString("DataTextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type.
        /// </summary>
        public static string DataType {
            get {
                return ResourceManager.GetString("DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Value Field.
        /// </summary>
        public static string DataValueField {
            get {
                return ResourceManager.GetString("DataValueField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal Precision.
        /// </summary>
        public static string DecimalPrecision {
            get {
                return ResourceManager.GetString("DecimalPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Static Code.
        /// </summary>
        public static string DefaultCodeStatic {
            get {
                return ResourceManager.GetString("DefaultCodeStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default DataType Code.
        /// </summary>
        public static string DefaultDataTypeCode {
            get {
                return ResourceManager.GetString("DefaultDataTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default DataType Name.
        /// </summary>
        public static string DefaultDataTypeName {
            get {
                return ResourceManager.GetString("DefaultDataTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Dynamic Method Name.
        /// </summary>
        public static string DefaultDynamicMethodName {
            get {
                return ResourceManager.GetString("DefaultDynamicMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value.
        /// </summary>
        public static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value Query.
        /// </summary>
        public static string DefaultValueQuery {
            get {
                return ResourceManager.GetString("DefaultValueQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Static Value.
        /// </summary>
        public static string DefaultValueStatic {
            get {
                return ResourceManager.GetString("DefaultValueStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value.
        /// </summary>
        public static string DefaultValueTypeCode {
            get {
                return ResourceManager.GetString("DefaultValueTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Mode.
        /// </summary>
        public static string DisplayMode {
            get {
                return ResourceManager.GetString("DisplayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Ready Script.
        /// </summary>
        public static string DocumentReadyScript {
            get {
                return ResourceManager.GetString("DocumentReadyScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable By.
        /// </summary>
        public static string EditableBy {
            get {
                return ResourceManager.GetString("EditableBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable By.
        /// </summary>
        public static string EditableBys {
            get {
                return ResourceManager.GetString("EditableBys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable Context.
        /// </summary>
        public static string EditableContext {
            get {
                return ResourceManager.GetString("EditableContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Dropdown Grouping.
        /// </summary>
        public static string EnableDropdownGrouping {
            get {
                return ResourceManager.GetString("EnableDropdownGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Column Width.
        /// </summary>
        public static string FieldColumnWidth {
            get {
                return ResourceManager.GetString("FieldColumnWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Html Attributes.
        /// </summary>
        public static string FieldHtmlAttributes {
            get {
                return ResourceManager.GetString("FieldHtmlAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field HtmlAttributes String.
        /// </summary>
        public static string FieldHtmlAttributesString {
            get {
                return ResourceManager.GetString("FieldHtmlAttributesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Id.
        /// </summary>
        public static string FieldId {
            get {
                return ResourceManager.GetString("FieldId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Name.
        /// </summary>
        public static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Partial View Name.
        /// </summary>
        public static string FieldPartialViewName {
            get {
                return ResourceManager.GetString("FieldPartialViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Serial No.
        /// </summary>
        public static string FieldSerialNo {
            get {
                return ResourceManager.GetString("FieldSerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Value Id.
        /// </summary>
        public static string FieldValueId {
            get {
                return ResourceManager.GetString("FieldValueId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Width Code.
        /// </summary>
        public static string FieldWidthCode {
            get {
                return ResourceManager.GetString("FieldWidthCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Add Button Name.
        /// </summary>
        public static string GridAddButtonName {
            get {
                return ResourceManager.GetString("GridAddButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Allow Filter.
        /// </summary>
        public static string GridAllowFilter {
            get {
                return ResourceManager.GetString("GridAllowFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Allow Paging.
        /// </summary>
        public static string GridAllowPaging {
            get {
                return ResourceManager.GetString("GridAllowPaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Allow Sorting.
        /// </summary>
        public static string GridAllowSorting {
            get {
                return ResourceManager.GetString("GridAllowSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Can Add.
        /// </summary>
        public static string GridCanAdd {
            get {
                return ResourceManager.GetString("GridCanAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Can Delete.
        /// </summary>
        public static string GridCanDelete {
            get {
                return ResourceManager.GetString("GridCanDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Can Edit.
        /// </summary>
        public static string GridCanEdit {
            get {
                return ResourceManager.GetString("GridCanEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Can View.
        /// </summary>
        public static string GridCanView {
            get {
                return ResourceManager.GetString("GridCanView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Columns.
        /// </summary>
        public static string GridColumns {
            get {
                return ResourceManager.GetString("GridColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Delete Button Name.
        /// </summary>
        public static string GridDeleteButtonName {
            get {
                return ResourceManager.GetString("GridDeleteButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Delete Confirmation Message.
        /// </summary>
        public static string GridDeleteConfirmationMessage {
            get {
                return ResourceManager.GetString("GridDeleteConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Delete Success Message.
        /// </summary>
        public static string GridDeleteSuccessMessage {
            get {
                return ResourceManager.GetString("GridDeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Edit Button Name.
        /// </summary>
        public static string GridEditButtonName {
            get {
                return ResourceManager.GetString("GridEditButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Maximum Rows.
        /// </summary>
        public static string GridMaximumRows {
            get {
                return ResourceManager.GetString("GridMaximumRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Minimum Rows.
        /// </summary>
        public static string GridMinimumRows {
            get {
                return ResourceManager.GetString("GridMinimumRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Page Size.
        /// </summary>
        public static string GridPageSize {
            get {
                return ResourceManager.GetString("GridPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Required Minimum Rows.
        /// </summary>
        public static string GridRequiredMinimumRows {
            get {
                return ResourceManager.GetString("GridRequiredMinimumRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Show Delete Confirmation.
        /// </summary>
        public static string GridShowDeleteConfirmation {
            get {
                return ResourceManager.GetString("GridShowDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid View Button Name.
        /// </summary>
        public static string GridViewButtonName {
            get {
                return ResourceManager.GetString("GridViewButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Template Field Id.
        /// </summary>
        public static string GroupTemplateFieldId {
            get {
                return ResourceManager.GetString("GroupTemplateFieldId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Info.
        /// </summary>
        public static string HelpInfo {
            get {
                return ResourceManager.GetString("HelpInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperlink Target.
        /// </summary>
        public static string HyperlinkTarget {
            get {
                return ResourceManager.GetString("HyperlinkTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inject Default Datasource Attributes.
        /// </summary>
        public static string InjectDefaultDatasourceAttributes {
            get {
                return ResourceManager.GetString("InjectDefaultDatasourceAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inject Default Label Attributes.
        /// </summary>
        public static string InjectDefaultLabelAttributes {
            get {
                return ResourceManager.GetString("InjectDefaultLabelAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is DataSource MultiValued.
        /// </summary>
        public static string IsDataSourceMultiValued {
            get {
                return ResourceManager.GetString("IsDataSourceMultiValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Label Italic?.
        /// </summary>
        public static string IsLabelItalic {
            get {
                return ResourceManager.GetString("IsLabelItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Label Underlined?.
        /// </summary>
        public static string IsLabelUnderlined {
            get {
                return ResourceManager.GetString("IsLabelUnderlined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Selection Multi Valued.
        /// </summary>
        public static string IsSelectionMultiValued {
            get {
                return ResourceManager.GetString("IsSelectionMultiValued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Visible.
        /// </summary>
        public static string IsVisible {
            get {
                return ResourceManager.GetString("IsVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Color Hexa.
        /// </summary>
        public static string LabelColorHexa {
            get {
                return ResourceManager.GetString("LabelColorHexa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Column Width.
        /// </summary>
        public static string LabelColumnWidth {
            get {
                return ResourceManager.GetString("LabelColumnWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Display Name.
        /// </summary>
        public static string LabelDisplayName {
            get {
                return ResourceManager.GetString("LabelDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Html Attributes.
        /// </summary>
        public static string LabelHtmlAttributes {
            get {
                return ResourceManager.GetString("LabelHtmlAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Html Attributes String.
        /// </summary>
        public static string LabelHtmlAttributesString {
            get {
                return ResourceManager.GetString("LabelHtmlAttributesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Value.
        /// </summary>
        public static string MaximumValue {
            get {
                return ResourceManager.GetString("MaximumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Value.
        /// </summary>
        public static string MinimumValue {
            get {
                return ResourceManager.GetString("MinimumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Lines.
        /// </summary>
        public static string NumberOfLines {
            get {
                return ResourceManager.GetString("NumberOfLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct Field.
        /// </summary>
        public static string PageTitleCorrect {
            get {
                return ResourceManager.GetString("PageTitleCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Field.
        /// </summary>
        public static string PageTitleCreate {
            get {
                return ResourceManager.GetString("PageTitleCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Field.
        /// </summary>
        public static string PageTitleDelete {
            get {
                return ResourceManager.GetString("PageTitleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct Template Field.
        /// </summary>
        public static string PageTitleTemplateCorrect {
            get {
                return ResourceManager.GetString("PageTitleTemplateCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Template Field.
        /// </summary>
        public static string PageTitleTemplateCreate {
            get {
                return ResourceManager.GetString("PageTitleTemplateCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Template Field - History.
        /// </summary>
        public static string PageTitleTemplateEditHistory {
            get {
                return ResourceManager.GetString("PageTitleTemplateEditHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Template Field.
        /// </summary>
        public static string PageTitleTemplateUpdate {
            get {
                return ResourceManager.GetString("PageTitleTemplateUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Field.
        /// </summary>
        public static string PageTitleUpdate {
            get {
                return ResourceManager.GetString("PageTitleUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartialView Name.
        /// </summary>
        public static string PartialViewName {
            get {
                return ResourceManager.GetString("PartialViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Holder.
        /// </summary>
        public static string PlaceHolder {
            get {
                return ResourceManager.GetString("PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup Height.
        /// </summary>
        public static string PopupHeight {
            get {
                return ResourceManager.GetString("PopupHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup Title.
        /// </summary>
        public static string PopupTitle {
            get {
                return ResourceManager.GetString("PopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup Width.
        /// </summary>
        public static string PopupWidth {
            get {
                return ResourceManager.GetString("PopupWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadOnly Client Script.
        /// </summary>
        public static string ReadOnlyClientScript {
            get {
                return ResourceManager.GetString("ReadOnlyClientScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadOnly Server Script.
        /// </summary>
        public static string ReadOnlyServerScript {
            get {
                return ResourceManager.GetString("ReadOnlyServerScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readonly.
        /// </summary>
        public static string ReadonlyTypeCode {
            get {
                return ResourceManager.GetString("ReadonlyTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Client Script.
        /// </summary>
        public static string RequiredClientScript {
            get {
                return ResourceManager.GetString("RequiredClientScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Server Script.
        /// </summary>
        public static string RequiredServerScript {
            get {
                return ResourceManager.GetString("RequiredServerScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Type.
        /// </summary>
        public static string RequiredTypeCode {
            get {
                return ResourceManager.GetString("RequiredTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence No.
        /// </summary>
        public static string SequenceNo {
            get {
                return ResourceManager.GetString("SequenceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Validation Script.
        /// </summary>
        public static string ServerValidationScript {
            get {
                return ResourceManager.GetString("ServerValidationScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show In Grid.
        /// </summary>
        public static string ShowInGrid {
            get {
                return ResourceManager.GetString("ShowInGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Required Asterisk.
        /// </summary>
        public static string ShowRequiredAsterisk {
            get {
                return ResourceManager.GetString("ShowRequiredAsterisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TemplateColumn Count.
        /// </summary>
        public static string TemplateColumnCount {
            get {
                return ResourceManager.GetString("TemplateColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Field Id.
        /// </summary>
        public static string TemplateFieldId {
            get {
                return ResourceManager.GetString("TemplateFieldId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Id.
        /// </summary>
        public static string TemplateId {
            get {
                return ResourceManager.GetString("TemplateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Maximum Column.
        /// </summary>
        public static string TemplateMaximumColumn {
            get {
                return ResourceManager.GetString("TemplateMaximumColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Tip.
        /// </summary>
        public static string ToolTip {
            get {
                return ResourceManager.GetString("ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewable By.
        /// </summary>
        public static string ViewableBy {
            get {
                return ResourceManager.GetString("ViewableBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewable By.
        /// </summary>
        public static string ViewableBys {
            get {
                return ResourceManager.GetString("ViewableBys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewable Context.
        /// </summary>
        public static string ViewableContext {
            get {
                return ResourceManager.GetString("ViewableContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility Client Script.
        /// </summary>
        public static string VisibilityClientScript {
            get {
                return ResourceManager.GetString("VisibilityClientScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility Server Script.
        /// </summary>
        public static string VisibilityServerScript {
            get {
                return ResourceManager.GetString("VisibilityServerScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility Type Code.
        /// </summary>
        public static string VisibilityTypeCode {
            get {
                return ResourceManager.GetString("VisibilityTypeCode", resourceCulture);
            }
        }
    }
}
