//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Translation.Nts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Report {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Report() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERP.Translation.Nts.Report", typeof(Report).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignee.
        /// </summary>
        public static string Assignee {
            get {
                return ResourceManager.GetString("Assignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to base64Img.
        /// </summary>
        public static string base64Img {
            get {
                return ResourceManager.GetString("base64Img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency ID.
        /// </summary>
        public static string DependencyID {
            get {
                return ResourceManager.GetString("DependencyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time zone.
        /// </summary>
        public static string EndTimezone {
            get {
                return ResourceManager.GetString("EndTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanded.
        /// </summary>
        public static string Expanded {
            get {
                return ResourceManager.GetString("Expanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is All Day.
        /// </summary>
        public static string IsAllDay {
            get {
                return ResourceManager.GetString("IsAllDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Of Value Id.
        /// </summary>
        public static string ListOfValueId {
            get {
                return ResourceManager.GetString("ListOfValueId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOV Type Id.
        /// </summary>
        public static string LOVTypeId {
            get {
                return ResourceManager.GetString("LOVTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Name.
        /// </summary>
        public static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string N_Active {
            get {
                return ResourceManager.GetString("N_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameLocal {
            get {
                return ResourceManager.GetString("NameLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nts Id.
        /// </summary>
        public static string NtsId {
            get {
                return ResourceManager.GetString("NtsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Id.
        /// </summary>
        public static string OrderId {
            get {
                return ResourceManager.GetString("OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent ID.
        /// </summary>
        public static string ParentID {
            get {
                return ResourceManager.GetString("ParentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent Complete.
        /// </summary>
        public static string PercentComplete {
            get {
                return ResourceManager.GetString("PercentComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predecessor ID.
        /// </summary>
        public static string PredecessorID {
            get {
                return ResourceManager.GetString("PredecessorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurrence Exception.
        /// </summary>
        public static string RecurrenceException {
            get {
                return ResourceManager.GetString("RecurrenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurrence Rule.
        /// </summary>
        public static string RecurrenceRule {
            get {
                return ResourceManager.GetString("RecurrenceRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurr Id.
        /// </summary>
        public static string RecurrId {
            get {
                return ResourceManager.GetString("RecurrId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Overdue.
        /// </summary>
        public static string S_RequestOverdue {
            get {
                return ResourceManager.GetString("S_RequestOverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Pending.
        /// </summary>
        public static string S_RequestPending {
            get {
                return ResourceManager.GetString("S_RequestPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence No.
        /// </summary>
        public static string SequenceNo {
            get {
                return ResourceManager.GetString("SequenceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time zone.
        /// </summary>
        public static string StartTimezone {
            get {
                return ResourceManager.GetString("StartTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Code.
        /// </summary>
        public static string StatusCode {
            get {
                return ResourceManager.GetString("StatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Name.
        /// </summary>
        public static string StatusName {
            get {
                return ResourceManager.GetString("StatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successor ID.
        /// </summary>
        public static string SuccessorID {
            get {
                return ResourceManager.GetString("SuccessorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Overdue.
        /// </summary>
        public static string T_AssignOverdue {
            get {
                return ResourceManager.GetString("T_AssignOverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Pending.
        /// </summary>
        public static string T_AssignPending {
            get {
                return ResourceManager.GetString("T_AssignPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamMember.
        /// </summary>
        public static string TeamMember {
            get {
                return ResourceManager.GetString("TeamMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Limited.
        /// </summary>
        public static string TitleLimited {
            get {
                return ResourceManager.GetString("TitleLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
    }
}
