using Synergy.App.Common;
using Synergy.App.DataModel;
using Synergy.App.ViewModel;
using Synergy.App.ViewModel.IMS;
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Text;
using System.Threading.Tasks;

namespace Synergy.App.Business
{
    public interface IInventoryManagementBusiness : IBusinessBase<ServiceViewModel, NtsService>
    {
        Task<IList<DirectSalesViewModel>> GetDirectSalesData(DirectSalesSearchViewModel model);
        Task<IList<ItemsViewModel>> GetDirectSaleItemsData(string directSalesId);
        Task<DirectSalesViewModel> GetDirectSalesData(string serviceId);
        Task<RequisitionViewModel> GetRequisitionData(string serviceId);
        Task<IList<RequisitionViewModel>> GetRequisitionDataByItemHead(string itemHead, string Customer, string status, string From, string To, string requisitionIds = null);
        Task<RequisitionViewModel> GetRequisitionDataByServiceId(string serviceId);
        Task<RequisitionViewModel> GetRequisitionDataById(string Id);
        Task<ItemsViewModel> GetItemsUnitDetailsByItemId(string itemId);
        Task<IList<ItemsViewModel>> GetItemsListData(ItemsSearchViewModel search);
        Task<IList<ItemsViewModel>> GetRequisistionItemsData(string requisitionId);
        Task<IList<IdNameViewModel>> GetItemCategoryByItemTypeId(string itemTypeId);
        Task<IList<IdNameViewModel>> GetItemSubCategoryByItemCategoryId(string itemCategoryId);
        Task<IList<IdNameViewModel>> GetItemByItemSubCategoryId(string itemSubCategoryId);
        Task<IList<RequisitionIssueItemsViewModel>> GetRequisistionItemsToIssue(string requisitionId);
        Task<IList<RequisitionIssueItemsViewModel>> GetRequisistionIssueItems(string issueServiceId, ImsIssueTypeEnum issueType);
        Task UpdateRequisitionServiceToIssued(string requisitionId);
        Task<IList<IssueRequisitionViewModel>> GetRequisistionIssue(string requisitionServiceId, ImsIssueTypeEnum issuetype);
        Task<IList<RequisitionViewModel>> GetIssueRequisitionData(string itemHead, string From, string To);
        Task<ItemsViewModel> GetItemsDetails(string id);
        Task<VendorViewModel> GetVendorDetailsById(string vendorId);
        Task<ItemShelfViewModel> GetItemShelfDetailsById(string itemSheflId);
        Task DeleteContacts(string id);
        Task<List<ItemShelfViewModel>> ReadShelfList();
        Task<ItemShelfViewModel> GetItemShelfDetail(string noteId);
        Task DeleteVendorCategories(string id);
        Task DeleteItemShelfCategories(string id);
        Task<List<VendorCategoryViewModel>> ReadCategoryNotInVendorCategoryData(string vendorId);
        Task<List<ItemShelfViewModel>> ReadCategoryNotInItemShelfCategoryData(string itemShelfId);
        Task<List<VendorCategoryViewModel>> ReadVendorCategoryData(string vendorId);
        Task<List<ItemShelfViewModel>> ReadItemShelfCategoryData(string itemShelfId);
        Task<List<ContactsViewModel>> ReadVendorContactsData(string vendorId);
        Task<IList<VendorViewModel>> GetVendorList(string countryId, string stateId, string cityId, string name);
        Task<CustomerViewModel> GetCustomerDetailsById(string customerId);
        Task DeleteCustomerContacts(string id);
        Task<List<POItemsViewModel>> GetRequisistionItemsByRequisitionId(string requisitionIds,bool isValidate=false);
        Task GeneratePOItems(string itemsData, string POId);

        Task GeneratePOItemsMobile(List<POItemsViewModel> items, string POId);
        Task GenerateInvoiceScheduleItems(string itemsData, string ISId);
        Task GenerateGoodsReceiptItems(string itemsData, string goodReceiptId, string warehouseId,string GoodsReceiptReferenceId,DateTime ReceiveDate);
        Task<List<ContactsViewModel>> ReadCustomerContactsData(string customerId);
        Task<List<IdNameViewModel>> GetItemCodeMappingList();
        Task<List<ItemStockViewModel>> ReadItemStockData(string itemTypeId, string itemCategory, string itemSubCategory, string warehouseId);
        Task<List<ItemStockViewModel>> ReadItemCurrentStockData(string warehouseId, string itemTypeId, string itemCategoryId, string itemSubCategoryId, string itemId);
        Task<ItemStockViewModel> GetUnitItemData(string Id);
        Task<ItemStockViewModel> GetItemHeaderData(string Id, string warehouseId);
        Task<IList<CustomerViewModel>> GetCustomerList(string countryId, string stateId, string cityId, string name);
        Task<CommandResult<InventoryItemViewModel>> InsertInventory(InventoryItemViewModel model);
        Task<IList<DeliveryNoteViewModel>> GetDeliveryNoteData(string itemHead, string From, string To);
        Task<DeliveryNoteReportViewModel> GetDeliveryNoteReportData(string deliveryNoteId);
        Task<PurchaseOrderReportViewModel> GetPurchaseOrderReportData(string purchaseOrderId);
        Task<ReceivedNoteReportViewModel> GetReceivedNoteReportData(string receivedNoteId);
        Task<PurchaseInvoiceReportViewModel> GetPurchaseInvoiceReportData(string purchaseInvoiceId);
        Task<List<InvoiceItemViewModel>> GetPurchaseInvoiceItemsList(string purchaseInvoiceId);
        Task<List<GoodsReceiptItemViewModel>> GetGoodReceiptItemsList(string receiptId);
        Task<List<DeliveryItemViewModel>> GetDeliveryItemsList(string deliveryNoteId);
        Task<List<IdNameViewModel>> ReadInvertoryFinancialYearIdNameList();
        Task<List<PurchaseInvoiceReportViewModel>> ReadInvoiceDetailsData(DateTime fromDate, DateTime toDate);
        Task<List<RequisitionIssueItemsViewModel>> ReadIssueTypeData(DateTime fromDate, DateTime toDate, string issueTypeId, string departmentId, string employeeId, string issueToTypeId);
        Task<List<ItemStockViewModel>> ReadItemHistoryData(DateTime fromDate, DateTime toDate, string warehouseId, string itemTypeId, string itemCategoryId, string itemSubCategoryId, string itemId);
        Task<List<StockTransferViewModel>> ReadItemTransferData(DateTime fromDate, DateTime toDate, string warehouseId, string itemTypeId, string itemCategoryId, string itemSubCategoryId, string itemId);
        Task<List<PurchaseOrderViewModel>> ReadPurchaseOrderStatusData(DateTime fromDate, DateTime toDate, string statusId);
        Task<List<PurchaseOrderViewModel>> ReadOrderBookData();
        Task<List<OrderSummaryViewModel>> ReadOrderStatusData(string financialYearId);
        Task<List<RequisitionViewModel>> ReadRequisitionByStatusData(DateTime fromDate, DateTime toDate, string typeId, string customerId, string statusId);
        Task<List<RequisitionViewModel>> ReadRequisitionByDetailsData(DateTime fromDate, DateTime toDate, string typeId, string customerId, string statusId);
        Task<List<GoodsReceiptViewModel>> ReadReceivedFromPOData(DateTime fromDate, DateTime toDate, string vendorId);
        Task<List<VendorCategoryViewModel>> ReadVendorCategoryData(string vendorId, string categoryId, string subCategoryId);
        Task<List<PurchaseReturnViewModel>> ReadReturnToVendorData(DateTime fromDate, DateTime toDate, string vendorId);
        Task<IList<RequisitionIssueItemsViewModel>> GetRequisistionIssueItemsByRequisitionId(string requisitionServiceId);
        Task<IList<RequisitionIssueItemsViewModel>> GetRequisitionIssueItemsByIssueRefId(string issueRefId);
        Task<List<PurchaseOrderViewModel>> GetVendorPOList(string itemHead = null, string vendorId = null, string statusId = null, string From = null, string To = null);
        Task<double> GetPOValueByPOId(string POId);
        Task UpdatePOValueInPO(string POId, double POValue);
        Task<ItemsViewModel> GetRequisitionItemById(string Id);
        Task<POItemsViewModel> GetPOItemById(string Id);
        Task<IList<GoodsReceiptItemViewModel>> GetGoodReceiptItemsByReceiptId(string receiptId);
        Task<IList<GoodsReceiptItemViewModel>> GetPOItemsByPOId(string poId);
        Task<IList<GoodsReceiptViewModel>> ReadDeliveryChallanData(string ItemHead, string Vendor, string From, string To, string poId, ImsReceiptTypeEnum? receiptType);
        Task<List<PurchaseOrderViewModel>> ReadPOData(string ItemHead, string Vendor, string From, string To);
        //Task<List<PurchaseOrderViewModel>> GetVendorPOList();
        Task<List<POItemsViewModel>> ReadPOItemsData(string poId);
        Task DeletePOItem(string poId);
        Task<IList<PurchaseOrderViewModel>> GetPOItemsData(string poId);
        Task<PurchaseOrderViewModel> GetPOData(string serviceId);
        Task<List<POTermsAndConditionsViewModel>> ReadPOTermsData(string poId);
        Task<IList<DirectSalesViewModel>> FilterDirectSalesData(DirectSalesSearchViewModel search);
        Task<bool> CheckItemStockExists(string itemId, string warehouseId);
        Task<double> GetClosingBalance(string itemId, string warehouseId);
        Task<GoodsReceiptItemViewModel> GetGoodReceiptItemById(string id);
        Task<List<RequisitionIssueItemsViewModel>> GetGoodReceiptItemsToIssue(string requisitionId, string itemId, string warehouseId, ImsReceiptTypeEnum receiptType);
        Task<IList<GoodsReceiptViewModel>> GetChallanDetailsbyPOId(string poId);
        Task UpdateStockClosingBalance(string itemId, string warehouseId, double closingBalance);        
        Task<GoodsReceiptItemViewModel> GetGoodReceiptItemDetails(string receiptId);
        Task<bool> UpdateInvoiceNoinGR(string Id, string invoiceNo);    
        Task<string> GetGoodReceiptItemIdByPoItemId(string id);
        Task<RequisitionIssueItemsViewModel> GetRequisistionIssueItemsById(string requisitionIssueItemId);
        Task<IList<StockTransferViewModel>> GetItemTransferredList(string from, string to, string challanNo);
        Task<List<ScheduleInvoiceViewModel>> GetRequisitiononFilters(string ItemHead, string From, string To);
        Task<List<ItemStockViewModel>> ReadItemListByStock(string itemTypeId, string itemCategory, string itemSubCategory, string warehouseId);

        Task<IList<StockTransferViewModel>> GetTransferItemsList(string stockTransferId);
        Task<List<POInvoiceViewModel>> GetPOInvoiceDetailsList(string poId);
        Task<bool> InvoiceNoExists(string invoiceNo);
        Task<List<SerialNoViewModel>> GetSerailNoByHeaderIdandReferenceId(string referenceId, string hearderId);
        Task<double> GetTotalQtyInHandCount();
        Task<double> GetTotalAllItem();
        Task<double> GetTotalItemsInHand();
        Task<double> GetTotalItemsToReceive();
        Task<double> GetTotalLowStockItems();
        Task<double> GetTotalAllItemGroupItems();
        Task<IList<IdNameViewModel>> GetTopSellingsItem(DateTime startDate, DateTime endDate);
        Task<double> GetPurchaseOrderQtyOrdered(DateTime startDate, DateTime endDate);
        Task<double> GetPurchaseOrderTotaCost(DateTime startDate, DateTime endDate);
        Task<IList<SalesOrder>> GetSalesOrderSummaryChart(DateTime startDate, DateTime endDate, InventoryDataFilterEnum filter);
        Task<double> GetDirectSalesAmountSummaryChart(DateTime item1, DateTime item2, InventoryDataFilterEnum filter);
        Task<List<ItemStockViewModel>> ReadStockEntriesData(string itemId, string warehouseId, DateTime? FromDate, DateTime? ToDate);
        Task updateSerialNosToIssued(string serialNoIds);
        Task<ItemStockViewModel> GetStockDetailsById(string stockId);
        Task<ItemStockViewModel> GetStockDataByNoteId(string stockNoteId);
        Task<List<ItemsViewModel>> GetActiveItemsFilterBySubCategory(string subCategoryId);
        Task<IList<DirectSalesViewModel>> GetDirectSalesList();
        Task<IList<SalesReturnViewModel>> GetSalesReturnList(string cusId, string From, string To, string serNo);
        Task<SalesReturnViewModel> GetSalesReturnData(string serId);
        Task<IList<SalesReturnViewModel>> GetSalesReturnItemsList(string salesReturnId);
        Task<IList<StockAdjustmentViewModel>> GetStockAdjustmentList();
        Task<IList<StockAdjustmentItemViewModel>> GetStockAdjustmentItemsData(string stockAdjustmentId);
        Task<IList<PurchaseReturnViewModel>> GetPurchaseReturnList(string cusId, string From, string To, string serNo);
        Task<PurchaseReturnViewModel> GetPurchaseReturnData(string serId);
        Task<List<SalesOrder>> GetItemValueByCategory();
        Task<List<SalesOrder>> GetItemValueByWarehouse();
        Task<StockAdjustmentViewModel> GetStockAdjustmentById(string stockAdjustmentId);
        Task<GoodsReceiptViewModel> GetGoodsReceiptById(string id);
        Task<IList<GoodsReceiptViewModel>> ReadGoodsReceiptData(string GoodsReceiptReferenceId, ImsReceiptTypeEnum receiptType);
        Task<List<PurchaseOrderViewModel>> GetPurchaseOrderList();
        Task<PurchaseOrderViewModel> GetPurchaseOrderData(string serviceId);
        Task<List<ItemsViewModel>> GetPurchaseOrderItemsList(string purchaseId);
        Task<List<PurchaseReturnViewModel>> GetPurchaseReturnItemsList(string purchaseReturnId);
        Task<GoodsReceiptViewModel> GetGoodsReceiptDataBySerId(string goodsReceiptServiceId);
        Task<IList<RequisitionIssueItemsViewModel>> GetRequisistionIssueItemsToDeliver(string requisitionId);
        Task UpdateDeliveryNoteAcknowledgement(string deliveryNoteId, string fileId);
        Task<DeliveryNoteViewModel> GetDeliveryNoteById(string deliveryNoteId);
        Task<List<ScheduleInvoiceViewModel>> ReadScheduleInvoice(string customerId);
        Task<StockTransferViewModel> GetTransferById(string stockTransferId);
        Task<IList<SalesReturnViewModel>> GetPurchaseReturnItemsData(string serviceId);
        Task<List<ItemsViewModel>> GetCRPFRequisitionItemList(string serviceId);
    }
}
