//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Data.GraphModel{
    
  
    public partial class NTS_NoteFieldValue : NodeBase
    {       
        //public long NoteId { get; set; }
        
       
        //public long TemplateId { get; set; }
      
        //public long TemplateFieldId { get; set; }
        
        public string Code { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }

    }
    public class R_NoteFieldValue_Note : RelationshipBase
    {

    }
    public class R_NoteFieldValue_TemplateField : RelationshipBase
    {

    }
}
