//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Translation.Sps {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SuccessionPlanningDashboard {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SuccessionPlanningDashboard() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERP.Translation.Sps.SuccessionPlanningDashboard", typeof(SuccessionPlanningDashboard).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string DdlOptionAll {
            get {
                return ResourceManager.GetString("DdlOptionAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By Team.
        /// </summary>
        public static string FilterTeam {
            get {
                return ResourceManager.GetString("FilterTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By User.
        /// </summary>
        public static string FilterUser {
            get {
                return ResourceManager.GetString("FilterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Succession Planning Document.
        /// </summary>
        public static string ManageSPDoc {
            get {
                return ResourceManager.GetString("ManageSPDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succession Cycles And Development Plan Shared With Me.
        /// </summary>
        public static string MySPCycleHeaderShared {
            get {
                return ResourceManager.GetString("MySPCycleHeaderShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Succession Cycle And Development Plan Status.
        /// </summary>
        public static string MySPSummaryDesc {
            get {
                return ResourceManager.GetString("MySPSummaryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Succession Planning Summary.
        /// </summary>
        public static string MySPSummaryHeader {
            get {
                return ResourceManager.GetString("MySPSummaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succession Planning Created By Me.
        /// </summary>
        public static string MySPSummaryHeaderCancelled {
            get {
                return ResourceManager.GetString("MySPSummaryHeaderCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succession Planning And Development Plan Created By Me.
        /// </summary>
        public static string MySPSummaryHeaderCreated {
            get {
                return ResourceManager.GetString("MySPSummaryHeaderCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succession Planning And Development Plan Shared With Me.
        /// </summary>
        public static string MySPSummaryHeaderShared {
            get {
                return ResourceManager.GetString("MySPSummaryHeaderShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Succession Planning Document.
        /// </summary>
        public static string MySPSummaryLnk {
            get {
                return ResourceManager.GetString("MySPSummaryLnk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks Assigned To Me .
        /// </summary>
        public static string MySPTaskAssigned {
            get {
                return ResourceManager.GetString("MySPTaskAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Succession Planning Task Summary.
        /// </summary>
        public static string MySPTaskPSummaryHeader {
            get {
                return ResourceManager.GetString("MySPTaskPSummaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks Shared With Me .
        /// </summary>
        public static string MySPTaskShared {
            get {
                return ResourceManager.GetString("MySPTaskShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Assigned To me.
        /// </summary>
        public static string MySPTaskSummaryLnk {
            get {
                return ResourceManager.GetString("MySPTaskSummaryLnk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status of Succession Cycles And Development Plan Shared With Team.
        /// </summary>
        public static string MySPTeamStatusHeader {
            get {
                return ResourceManager.GetString("MySPTeamStatusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succession Planning And Development Plan Shared With Team.
        /// </summary>
        public static string MySPTeamStatusHeaderShared {
            get {
                return ResourceManager.GetString("MySPTeamStatusHeaderShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Team Succession Planning Summary.
        /// </summary>
        public static string MySPTeamSummaryHeader {
            get {
                return ResourceManager.GetString("MySPTeamSummaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succession Planning And Development Plan Created By Team .
        /// </summary>
        public static string MySPTeamSummaryHeaderCreated {
            get {
                return ResourceManager.GetString("MySPTeamSummaryHeaderCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succession Cycle And Development Plan Status Of Team.
        /// </summary>
        public static string MySPTeamSummaryLnk {
            get {
                return ResourceManager.GetString("MySPTeamSummaryLnk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Assigned To Team.
        /// </summary>
        public static string MySPTeamTaskAssigned {
            get {
                return ResourceManager.GetString("MySPTeamTaskAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Shared With Team.
        /// </summary>
        public static string MySPTeamTaskShared {
            get {
                return ResourceManager.GetString("MySPTeamTaskShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks Shared With Team.
        /// </summary>
        public static string MySPTeamTasksShared {
            get {
                return ResourceManager.GetString("MySPTeamTasksShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Team Succession Planning And Development Plan Task Summary.
        /// </summary>
        public static string MySPTeamTaskSummaryHeader {
            get {
                return ResourceManager.GetString("MySPTeamTaskSummaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue.
        /// </summary>
        public static string Overdue {
            get {
                return ResourceManager.GetString("Overdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succession Planning Summary - .
        /// </summary>
        public static string TabSPSummary {
            get {
                return ResourceManager.GetString("TabSPSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succession Planning Worksheet.
        /// </summary>
        public static string TabSPWorksheet {
            get {
                return ResourceManager.GetString("TabSPWorksheet", resourceCulture);
            }
        }
    }
}
