//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ERP.Utility;
using System;

namespace ERP.Data.GraphModel
{
    public partial class ADM_SlavePullLog : NodeBase
    {       
        public PullTypeEnum PullType { get; set; }        
        public string ResponseMessage { get; set; }
        public DateTime? FromDate { get; set; }
        public DateTime? ToDate { get; set; }
        public string RequestQuery { get; set; }
        public bool? ApiResponseStatus { get; set; }
    }   
}
