//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ERP.Utility;
using System;

namespace ERP.Data.GraphModel
{

    public partial class ADM_ApplicationLicense : NodeBase
    {
        public string LicenseKey { get; set; }
        public string ServerIpAddress { get; set; }
        public LicenseTypeEnum LicenseType { get; set; }
        public long? NumberOfUsers { get; set; }
        public DateTime EffectiveStartDate { get; set; }
        public DateTime? EffectiveEndDate { get; set; }
    }
    public class R_ApplicationLicense_Customer : RelationshipBase
    {

    }
}
