//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Data.Model
{
    using System;
    
    public partial class ADM_UserField : AdminBase
    {
        public ulong UserFieldId { get; set; }
        public ulong UserId { get; set; }
        public ulong FieldId { get; set; }
        public ulong ScreenId { get; set; }
    }
}
