version: '3.1'

services:
 registry:
  restart: always
  image: registry:2
  ports:
    - 5001:5000
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/aitalkx.crt
    REGISTRY_HTTP_TLS_KEY: /certs/aitalkx.key
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  volumes:
      - type: volume
        source: registry
        target: /var/lib/registry
      #- /path/data:/var/lib/registry
      - ../nginx/aitalkxcert:/certs
      - ./auth:/auth

volumes:
  registry:

networks:
  default:
    external:
      name: cmssynergy_default