//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERP.Translation.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request has been submitted successfully.
        /// </summary>
        public static string AlertSubmitSuccess {
            get {
                return ResourceManager.GetString("AlertSubmitSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcements.
        /// </summary>
        public static string Announcements {
            get {
                return ResourceManager.GetString("Announcements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select atleast one action from the list.
        /// </summary>
        public static string AtleastOneActionRequired {
            get {
                return ResourceManager.GetString("AtleastOneActionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select atleast one role from the list.
        /// </summary>
        public static string AtleastOneRoleRequired {
            get {
                return ResourceManager.GetString("AtleastOneRoleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select atleast one rule from the list.
        /// </summary>
        public static string AtleastOneRuleRequired {
            get {
                return ResourceManager.GetString("AtleastOneRuleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Reason.
        /// </summary>
        public static string CancelReason {
            get {
                return ResourceManager.GetString("CancelReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel reason is required.
        /// </summary>
        public static string CancelReasonMessage {
            get {
                return ResourceManager.GetString("CancelReasonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete this item.
        /// </summary>
        public static string CannotDelete {
            get {
                return ResourceManager.GetString("CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Closed successfully.
        /// </summary>
        public static string CloseSuccess {
            get {
                return ResourceManager.GetString("CloseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Home.
        /// </summary>
        public static string CompanyHomePageTitle {
            get {
                return ResourceManager.GetString("CompanyHomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Post.
        /// </summary>
        public static string CompanyPost {
            get {
                return ResourceManager.GetString("CompanyPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion Reason.
        /// </summary>
        public static string CompletionReason {
            get {
                return ResourceManager.GetString("CompletionReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion reason is required.
        /// </summary>
        public static string CompletionReasonMessage {
            get {
                return ResourceManager.GetString("CompletionReasonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data correction successfully completed.
        /// </summary>
        public static string CorrectionSuccess {
            get {
                return ResourceManager.GetString("CorrectionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a post....
        /// </summary>
        public static string CreateAPost {
            get {
                return ResourceManager.GetString("CreateAPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Service.
        /// </summary>
        public static string CreateService {
            get {
                return ResourceManager.GetString("CreateService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate Reason.
        /// </summary>
        public static string DelegateReason {
            get {
                return ResourceManager.GetString("DelegateReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate reason is required.
        /// </summary>
        public static string DelegateReasonMessage {
            get {
                return ResourceManager.GetString("DelegateReasonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected item(s)?.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot undo this action. Are you sure you want to proceed with this action?.
        /// </summary>
        public static string DeleteConfirm2 {
            get {
                return ResourceManager.GetString("DeleteConfirm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete this item.
        /// </summary>
        public static string DeleteForeignKeyMessage {
            get {
                return ResourceManager.GetString("DeleteForeignKeyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected item(s) deleted successfully.
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe Your Group.
        /// </summary>
        public static string DescribeGroup {
            get {
                return ResourceManager.GetString("DescribeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire in.
        /// </summary>
        public static string Expirein {
            get {
                return ResourceManager.GetString("Expirein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &quot;Continue&quot; to keep working, or &quot;Log Out&quot; if you are finished.12.
        /// </summary>
        public static string ExpiryMessage {
            get {
                return ResourceManager.GetString("ExpiryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extension not supported!.
        /// </summary>
        public static string FileExtNotSupported {
            get {
                return ResourceManager.GetString("FileExtNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Upload.
        /// </summary>
        public static string FileUploadFailed {
            get {
                return ResourceManager.GetString("FileUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This browser doesn&apos;t support HTML5 file uploads!.
        /// </summary>
        public static string FileUploadFailedForBrowser {
            get {
                return ResourceManager.GetString("FileUploadFailedForBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, File is Uploading .........
        /// </summary>
        public static string FileUploading {
            get {
                return ResourceManager.GetString("FileUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto Company Home Page.
        /// </summary>
        public static string GotoCompanyHomePage {
            get {
                return ResourceManager.GetString("GotoCompanyHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manpower.
        /// </summary>
        public static string ImgAltManpower {
            get {
                return ResourceManager.GetString("ImgAltManpower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Management.
        /// </summary>
        public static string ImgAltPerformanceManagement {
            get {
                return ResourceManager.GetString("ImgAltPerformanceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succession Planning.
        /// </summary>
        public static string ImgAltSuccessionPlanning {
            get {
                return ResourceManager.GetString("ImgAltSuccessionPlanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string ImgAltWelcome {
            get {
                return ResourceManager.GetString("ImgAltWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worklist.
        /// </summary>
        public static string ImgAltWorklist {
            get {
                return ResourceManager.GetString("ImgAltWorklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Notes.
        /// </summary>
        public static string ImgTitleActiveNotes {
            get {
                return ResourceManager.GetString("ImgTitleActiveNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Announcement.
        /// </summary>
        public static string ImgTitleAddAnnouncement {
            get {
                return ResourceManager.GetString("ImgTitleAddAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string ImgTitleGroup {
            get {
                return ResourceManager.GetString("ImgTitleGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string ImgTitleNotes {
            get {
                return ResourceManager.GetString("ImgTitleNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Service.
        /// </summary>
        public static string ImgTitlePendingService {
            get {
                return ResourceManager.GetString("ImgTitlePendingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Task.
        /// </summary>
        public static string ImgTitlePendingTask {
            get {
                return ResourceManager.GetString("ImgTitlePendingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string ImgTitleService {
            get {
                return ResourceManager.GetString("ImgTitleService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string ImgTitleTask {
            get {
                return ResourceManager.GetString("ImgTitleTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Saved Successfully! .
        /// </summary>
        public static string InsertQuery {
            get {
                return ResourceManager.GetString("InsertQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data inserted successfully.
        /// </summary>
        public static string InsertSuccess {
            get {
                return ResourceManager.GetString("InsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Operation.
        /// </summary>
        public static string InvalidOperation {
            get {
                return ResourceManager.GetString("InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This {0} already exists..
        /// </summary>
        public static string ItemExist {
            get {
                return ResourceManager.GetString("ItemExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping added successfully.
        /// </summary>
        public static string MappingAdded {
            get {
                return ResourceManager.GetString("MappingAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping removed successfully.
        /// </summary>
        public static string MappingRemoved {
            get {
                return ResourceManager.GetString("MappingRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Job Title.
        /// </summary>
        public static string NoJobTitle {
            get {
                return ResourceManager.GetString("NoJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Department.
        /// </summary>
        public static string NoOrganization {
            get {
                return ResourceManager.GetString("NoOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Record Found.
        /// </summary>
        public static string NoRecordFound {
            get {
                return ResourceManager.GetString("NoRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department change saved successfully.
        /// </summary>
        public static string OrganizationSaveChanged {
            get {
                return ResourceManager.GetString("OrganizationSaveChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Brands.
        /// </summary>
        public static string OurBrands {
            get {
                return ResourceManager.GetString("OurBrands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current request is pending with the task owner. You cannot raise another request now..
        /// </summary>
        public static string PendingRequestMessage {
            get {
                return ResourceManager.GetString("PendingRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position change saved successfully.
        /// </summary>
        public static string PositionSaveChanged {
            get {
                return ResourceManager.GetString("PositionSaveChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting To.
        /// </summary>
        public static string PostingTo {
            get {
                return ResourceManager.GetString("PostingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejection Reason.
        /// </summary>
        public static string RejectionReason {
            get {
                return ResourceManager.GetString("RejectionReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejection reason is required.
        /// </summary>
        public static string RejectionReasonMessage {
            get {
                return ResourceManager.GetString("RejectionReasonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem in Releasing, Please Contact Administrator.
        /// </summary>
        public static string ReleasingProblemMessage {
            get {
                return ResourceManager.GetString("ReleasingProblemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Submitted successfully.
        /// </summary>
        public static string RequestSubmitSuccess {
            get {
                return ResourceManager.GetString("RequestSubmitSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required fields.
        /// </summary>
        public static string Requiredfields {
            get {
                return ResourceManager.GetString("Requiredfields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Reason.
        /// </summary>
        public static string ReturnReason {
            get {
                return ResourceManager.GetString("ReturnReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return reason is required.
        /// </summary>
        public static string ReturnReasonMessage {
            get {
                return ResourceManager.GetString("ReturnReasonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search For The Group.
        /// </summary>
        public static string SearchGroup {
            get {
                return ResourceManager.GetString("SearchGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select --.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A server error has occurred!.
        /// </summary>
        public static string ServerErrorMsg {
            get {
                return ResourceManager.GetString("ServerErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Expired.
        /// </summary>
        public static string SessionExpired {
            get {
                return ResourceManager.GetString("SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has been expired. Click &apos;OK&apos; button to login again..
        /// </summary>
        public static string SessionExpiredMsg {
            get {
                return ResourceManager.GetString("SessionExpiredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session will expire in :.
        /// </summary>
        public static string SessionExpiry {
            get {
                return ResourceManager.GetString("SessionExpiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data updated successfully.
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
    }
}
