//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ERP.Utility;
using System;
using System.Linq;

namespace ERP.Data.GraphModel
{
  
    public partial class HRS_AssignmentRoot : RootNodeBase
    {

    }
  
    public partial class HRS_Assignment : NodeDatedBase
    {
        [NotMapped]
        public long AssignmentId { get; set; }
        public ApprovalStatusEnum ApprovalStatus { get; set; }
        [NotMapped]
        public string AssignmentStatus;
        public string ClassOfTravelCode { get; set; }
        public bool PayAnnualTicketForSelf { get; set; }
        public bool PayAnnualTicketForDependent { get; set; }
        public bool IsPrimaryAssignment { get; set; }
        //public string BiometricId { get; set; }
        public DateTime? DateOfJoin { get; set; }
        public DateTime? ProbationEndDate { get; set; }
        public DateTime? NoticeStartDate { get; set; }
        public DateTime? ActualTerminationDate { get; set; }
        public ProbationPeriodEnum? ProbationPeriod { get; set; }
        public int? NoticePeriod { get; set; }
        public string Email { get; set; }
        public string WorkPhone { get; set; }
        public string WorkPhoneExtension { get; set; }
        //[NotMapped]
        //public bool IsActive <DateTime? asofDate = null>  { get; set; }

        public ReasonForLeavingEnum? ReasonForLeaving { get; set; }
    }

    public class R_AssignmentRoot : RelationshipDatedBase
    {

    }
    public class R_AssignmentRoot_PersonRoot : RelationshipBase
    {

    }
    public class R_Assignment_GradeRoot : RelationshipBase
    {

    }

    public class R_Assignment_OrganizationRoot : RelationshipBase
    {

    }

    public class R_Assignment_JobRoot : RelationshipBase
    {

    }

    public class R_Assignment_PositionRoot : RelationshipBase
    {

    }

    public class R_Assignment_Location : RelationshipBase
    {

    }

    public class R_Assignment_Supervisor_PersonRoot : RelationshipBase
    {

    }

    public class R_Assignment_TicketDestination : RelationshipBase
    {

    }

    public class R_Assignment_AssignmentType_ListOfValue : RelationshipBase
    {

    }

    public class R_Assignment_AssignmentStatus : RelationshipBase
    {

    }
    public class R_Assignment_Section : RelationshipBase
    {

    }
    public partial class HRS_Assignment_Logs : HRS_Assignment
    {
        public string PersonFullName { get; set; }
        public string PersonNo { get; set; }
        public string AssignmentTypeCode { get; set; }
        public string LocationName { get; set; }
        public string GradeName { get; set; }
        public string AssignmentTypeName { get; set; }

        public long? PhotoId { get; set; }
        public string OrganizationName { get; set; }
        public string JobName { get; set; }
        public string PositionName { get; set; }
        public string SupervisorName { get; set; }
        public string SectionName { get; set; }
        public string AssignmentStatusName { get; set; }
        public string TicketDestination { get; set; }
    }
}

