//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using ERP.Utility;

namespace ERP.Data.GraphModel
{

    [CompanyNotRequired]
    public partial class HRS_PositionHierarchyRoot : RootNodeBase
    {

    }
    [CompanyNotRequired]
    public partial class HRS_PositionHierarchy : NodeDatedBase
    {      
        public long PositionHierarchyId { get; set; }
        public string Remarks { get; set; }
        public ApprovalStatusEnum ApprovalStatus { get; set; }
        public override bool IsActive(DateTime? asofDate = null)
        {
            return base.IsActive(asofDate) && ApprovalStatus == ApprovalStatusEnum.Approved;
        }
    }
    public class R_PositionHierarchyRoot : RelationshipDatedBase
    {

    }
    public class R_PositionHierarchyRoot_Hierarchy : RelationshipBase
    {

    }
    public class R_PositionHierarchyRoot_PositionRoot : RelationshipBase
    {

    }
    public class R_PositionHierarchy_Parent_PositionRoot : RelationshipBase
    {

    }
}
