FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /app
COPY *.sln .
COPY NuGet.Config .
COPY CMS.UI.Web/*.csproj ./CMS.UI.Web/
COPY CMS.UI.Web/LocalDependencies/ ./CMS.UI.Web/LocalDependencies/
COPY CMS.Business/*.csproj ./CMS.Business/
COPY CMS.Common/*.csproj ./CMS.Common/
COPY CMS.Data.Model/*.csproj ./CMS.Data.Model/
COPY CMS.Data.Repository/*.csproj ./CMS.Data.Repository/
COPY CMS.UI.ViewModel/*.csproj ./CMS.UI.ViewModel/
COPY CMS.Web.Api/*.csproj ./CMS.Web.Api/
COPY CMS.Web.Scheduler/*.csproj ./CMS.Web.Scheduler/
RUN dotnet restore

COPY . .

WORKDIR /app/CMS.UI.ViewModel
RUN dotnet publish -c SchedulerRelease -o /out --no-restore

WORKDIR /app/CMS.Data.Repository
RUN dotnet publish -c SchedulerRelease -o /out --no-restore

WORKDIR /app/CMS.Data.Model
RUN dotnet publish -c SchedulerRelease -o /out --no-restore

WORKDIR /app/CMS.Common
RUN dotnet publish -c SchedulerRelease -o /out --no-restore

WORKDIR /app/CMS.Business
RUN dotnet publish -c SchedulerRelease -o /out --no-restore

#WORKDIR /app/CMS.ReportLibrary
#RUN dotnet publish -c SchedulerRelease -o /out --no-restore

#WORKDIR /app/CMS.UI.Web
#RUN dotnet publish -c SchedulerRelease -o /out --no-restore

WORKDIR /app/CMS.Web.Scheduler
RUN dotnet publish -c SchedulerRelease -o /out --no-restore

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS runtime
WORKDIR /app 

COPY --from=build /out ./

ENV ASPNETCORE_ENVIRONMENT Production
ENV ASPNETCORE_URLS http://*:5000
ENTRYPOINT ["dotnet", "CMS.Web.Scheduler.dll"]

