//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ERP.Utility;
using System;
using System.Collections.Generic;
using System.Linq;

namespace ERP.Data.GraphModel
{
    public partial class GEN_Schedule : NodeBase
    {        
        public ScheduleEnum ScheduleFor { get; set; }
       
        public int? Recurrence { get; set; }
        public TimeSpan? StartTime { get; set; }
        public TimeSpan? EndTime { get; set; }
        public TimeSpan? Duration { get; set; }

        public RecurrencePatternEnum RecurrencePattern { get; set; }
        public int? RecurrenceInterval { get; set; }

        public DailyRecurrenceTypeEnum? DailyRecurrenceType { get; set; }

       // public ICollection<WeekDay> WeeklyRecurrenceDays { get; set; }

        public MonthlyRecurrenceTypeEnum? MonthlyRecurrenceType { get; set; }
        public int? MonthlyRecurrenceDate { get; set; }
        public int? MonthlyRecurrenceWeekNumber { get; set; }
        public WeekDay? MonthlyRecurrenceWeekDay { get; set; }

        public YearlyRecurrenceTypeEnum? YearlyRecurrenceType { get; set; }
        public int? YearlyRecurrenceMonth { get; set; }
        public int? YearlyRecurrenceMonthDate { get; set; }

        public int? YearlyRecurrenceWeekNumber { get; set; }
        public WeekDay? YearlyRecurrenceWeekDay { get; set; }
        public int? YearlyRecurrenceWeekDayMonth { get; set; }

        public DateTime StartDate { get; set; }
        public ScheduleEndTypeEnum ScheduleEndType { get; set; }
        public int? EndAfterRecurrence { get; set; }
        public DateTime? EndByDate { get; set; }

        public bool Sunday { get; set; }
        public bool Monday { get; set; }
        public bool Tuesday { get; set; }
        public bool Wednesday { get; set; }
        public bool Thursday { get; set; }
        public bool Friday { get; set; }
        public bool Saturday { get; set; }

        public string Description { get; set; }
    }
    public class R_Schedule_Reference : RelationshipBase
    {
        public ReferenceTypeEnum? ReferenceTypeCode { get; set; }
    }

}
