//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Data.GraphModel
{
  
    public partial class GEN_Sequence : NodeBase
    {
        public string Name { get; set; }
        public long  NextId { get; set; }
        
    }
}
