//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using ERP.Utility;
using System;
using System.Linq;

namespace ERP.Data.GraphModel
{

    public partial class GEN_ActivityLog : NodeBase
    {
        public long? UserId { get; set; }
        public DataOperationEvent? EventType { get; set; }
        public string EventDescription { get; set; }
        public NodeEnum? ReferenceNode { get; set; }
        public long? ReferenceId { get; set; }
        public string Url { get; set; }
        public string QueryString { get; set; }
        public DataSourceEnum? RequestSource { get; set; }
        public LayoutModeEnum? LayoutMode { get; set; }
        
    }



}
