//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ERP.Utility;
using System;

namespace ERP.Data.GraphModel
{
    public partial class REC_RecruitmentProcess : NodeBase
    {
        public ProcessStatusEnum ProcessStatus { get; set; }
        public DateTime ProcessStartDate { get; set; }
    }
    public class R_RecruitmentProcess_Application : RelationshipBase
    {
        public bool IsLineManagerSelected { get; set; }
    }
    public class R_RecruitmentProcess_JobRequest : RelationshipBase
    {

    }
}
