//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace ERP.Data.GraphModel
{
  
    public partial class NTS_ServiceMultipleFieldValueVersion : NTS_ServiceMultipleFieldValue
    {
        public long VersionedByUserId { get; set; }
        public DateTime VersionedDate { get; set; }
    }
    public class R_ServiceMultipleFieldValueVersion_ServiceVersion : RelationshipBase
    {

    }
    public class R_ServiceMultipleFieldValueVersion_TemplateField : RelationshipBase
    {

    }
}
