START TRANSACTION;

CREATE TABLE public."FormResourceLanguage" (
    "Id" text COLLATE cms_collation_ci NOT NULL,
    "FormTableId" text COLLATE cms_collation_ci NULL,
    "ColumnId" text COLLATE cms_collation_ci NULL,
    "English" text COLLATE cms_collation_ci NULL,
    "Arabic" text COLLATE cms_collation_ci NULL,
    "Hindi" text COLLATE cms_collation_ci NULL,
    "EnglishHelperText" text COLLATE cms_collation_ci NULL,
    "ArabicHelperText" text COLLATE cms_collation_ci NULL,
    "HindiHelperText" text COLLATE cms_collation_ci NULL,
    "EnglishTooltip" text COLLATE cms_collation_ci NULL,
    "ArabicTooltip" text COLLATE cms_collation_ci NULL,
    "HindiTooltip" text COLLATE cms_collation_ci NULL,
    "CreatedDate" timestamp without time zone NOT NULL,
    "CreatedBy" text COLLATE cms_collation_ci NULL,
    "LastUpdatedDate" timestamp without time zone NOT NULL,
    "LastUpdatedBy" text COLLATE cms_collation_ci NULL,
    "IsDeleted" boolean NOT NULL,
    "SequenceOrder" bigint NULL,
    "CompanyId" text COLLATE cms_collation_ci NULL,
    "LegalEntityId" text COLLATE cms_collation_ci NULL,
    "Status" integer NOT NULL,
    "VersionNo" bigint NOT NULL,
    "PortalId" text COLLATE cms_collation_ci NULL,
    CONSTRAINT "PK_FormResourceLanguage" PRIMARY KEY ("Id")
);

CREATE TABLE log."FormResourceLanguageLog" (
    "Id" text COLLATE cms_collation_ci NOT NULL,
    "RecordId" text COLLATE cms_collation_ci NULL,
    "LogVersionNo" bigint NOT NULL,
    "IsLatest" boolean NOT NULL,
    "LogStartDate" timestamp without time zone NOT NULL,
    "LogEndDate" timestamp without time zone NOT NULL,
    "LogStartDateTime" timestamp without time zone NOT NULL,
    "LogEndDateTime" timestamp without time zone NOT NULL,
    "IsDatedLatest" boolean NOT NULL,
    "IsVersionLatest" boolean NOT NULL,
    "CreatedDate" timestamp without time zone NOT NULL,
    "CreatedBy" text COLLATE cms_collation_ci NULL,
    "LastUpdatedDate" timestamp without time zone NOT NULL,
    "LastUpdatedBy" text COLLATE cms_collation_ci NULL,
    "IsDeleted" boolean NOT NULL,
    "SequenceOrder" bigint NULL,
    "CompanyId" text COLLATE cms_collation_ci NULL,
    "LegalEntityId" text COLLATE cms_collation_ci NULL,
    "DataAction" integer NOT NULL,
    "Status" integer NOT NULL,
    "VersionNo" bigint NOT NULL,
    "PortalId" text COLLATE cms_collation_ci NULL,
    "FormTableId" text COLLATE cms_collation_ci NULL,
    "ColumnId" text COLLATE cms_collation_ci NULL,
    "English" text COLLATE cms_collation_ci NULL,
    "Arabic" text COLLATE cms_collation_ci NULL,
    "Hindi" text COLLATE cms_collation_ci NULL,
    "EnglishHelperText" text COLLATE cms_collation_ci NULL,
    "ArabicHelperText" text COLLATE cms_collation_ci NULL,
    "HindiHelperText" text COLLATE cms_collation_ci NULL,
    "EnglishTooltip" text COLLATE cms_collation_ci NULL,
    "ArabicTooltip" text COLLATE cms_collation_ci NULL,
    "HindiTooltip" text COLLATE cms_collation_ci NULL,
    CONSTRAINT "PK_FormResourceLanguageLog" PRIMARY KEY ("Id")
);

CREATE TABLE public."NoteResourceLanguage" (
    "Id" text COLLATE cms_collation_ci NOT NULL,
    "TemplateId" text COLLATE cms_collation_ci NULL,
    "NoteTableId" text COLLATE cms_collation_ci NULL,
    "ColumnId" text COLLATE cms_collation_ci NULL,
    "English" text COLLATE cms_collation_ci NULL,
    "Arabic" text COLLATE cms_collation_ci NULL,
    "Hindi" text COLLATE cms_collation_ci NULL,
    "EnglishHelperText" text COLLATE cms_collation_ci NULL,
    "ArabicHelperText" text COLLATE cms_collation_ci NULL,
    "HindiHelperText" text COLLATE cms_collation_ci NULL,
    "EnglishTooltip" text COLLATE cms_collation_ci NULL,
    "ArabicTooltip" text COLLATE cms_collation_ci NULL,
    "HindiTooltip" text COLLATE cms_collation_ci NULL,
    "CreatedDate" timestamp without time zone NOT NULL,
    "CreatedBy" text COLLATE cms_collation_ci NULL,
    "LastUpdatedDate" timestamp without time zone NOT NULL,
    "LastUpdatedBy" text COLLATE cms_collation_ci NULL,
    "IsDeleted" boolean NOT NULL,
    "SequenceOrder" bigint NULL,
    "CompanyId" text COLLATE cms_collation_ci NULL,
    "LegalEntityId" text COLLATE cms_collation_ci NULL,
    "Status" integer NOT NULL,
    "VersionNo" bigint NOT NULL,
    "PortalId" text COLLATE cms_collation_ci NULL,
    CONSTRAINT "PK_NoteResourceLanguage" PRIMARY KEY ("Id")
);

CREATE TABLE log."NoteResourceLanguageLog" (
    "Id" text COLLATE cms_collation_ci NOT NULL,
    "RecordId" text COLLATE cms_collation_ci NULL,
    "LogVersionNo" bigint NOT NULL,
    "IsLatest" boolean NOT NULL,
    "LogStartDate" timestamp without time zone NOT NULL,
    "LogEndDate" timestamp without time zone NOT NULL,
    "LogStartDateTime" timestamp without time zone NOT NULL,
    "LogEndDateTime" timestamp without time zone NOT NULL,
    "IsDatedLatest" boolean NOT NULL,
    "IsVersionLatest" boolean NOT NULL,
    "CreatedDate" timestamp without time zone NOT NULL,
    "CreatedBy" text COLLATE cms_collation_ci NULL,
    "LastUpdatedDate" timestamp without time zone NOT NULL,
    "LastUpdatedBy" text COLLATE cms_collation_ci NULL,
    "IsDeleted" boolean NOT NULL,
    "SequenceOrder" bigint NULL,
    "CompanyId" text COLLATE cms_collation_ci NULL,
    "LegalEntityId" text COLLATE cms_collation_ci NULL,
    "DataAction" integer NOT NULL,
    "Status" integer NOT NULL,
    "VersionNo" bigint NOT NULL,
    "PortalId" text COLLATE cms_collation_ci NULL,
    "TemplateId" text COLLATE cms_collation_ci NULL,
    "NoteTableId" text COLLATE cms_collation_ci NULL,
    "ColumnId" text COLLATE cms_collation_ci NULL,
    "English" text COLLATE cms_collation_ci NULL,
    "Arabic" text COLLATE cms_collation_ci NULL,
    "Hindi" text COLLATE cms_collation_ci NULL,
    "EnglishHelperText" text COLLATE cms_collation_ci NULL,
    "ArabicHelperText" text COLLATE cms_collation_ci NULL,
    "HindiHelperText" text COLLATE cms_collation_ci NULL,
    "EnglishTooltip" text COLLATE cms_collation_ci NULL,
    "ArabicTooltip" text COLLATE cms_collation_ci NULL,
    "HindiTooltip" text COLLATE cms_collation_ci NULL,
    CONSTRAINT "PK_NoteResourceLanguageLog" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220617143355_S_20220617_3', '5.0.2');

COMMIT;

