//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MenuItems {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuItems() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERP.Translation.MenuItems", typeof(MenuItems).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Announcement.
        /// </summary>
        public static string AddAnnouncement {
            get {
                return ResourceManager.GetString("AddAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Settings.
        /// </summary>
        public static string AdminSettings {
            get {
                return ResourceManager.GetString("AdminSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcements.
        /// </summary>
        public static string Announcements {
            get {
                return ResourceManager.GetString("Announcements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Data.
        /// </summary>
        public static string ApplicationData {
            get {
                return ResourceManager.GetString("ApplicationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Home.
        /// </summary>
        public static string CompanyHome {
            get {
                return ResourceManager.GetString("CompanyHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Group.
        /// </summary>
        public static string CreateGroup {
            get {
                return ResourceManager.GetString("CreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant Access.
        /// </summary>
        public static string GrantAccess {
            get {
                return ResourceManager.GetString("GrantAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarchies.
        /// </summary>
        public static string Hierarchies {
            get {
                return ResourceManager.GetString("Hierarchies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR Direct.
        /// </summary>
        public static string HRDirect {
            get {
                return ResourceManager.GetString("HRDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Performance Document.
        /// </summary>
        public static string ManagePerformanceDocument {
            get {
                return ResourceManager.GetString("ManagePerformanceDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Person.
        /// </summary>
        public static string ManagePerson {
            get {
                return ResourceManager.GetString("ManagePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Succession Planning.
        /// </summary>
        public static string ManageSuccessionPlanning {
            get {
                return ResourceManager.GetString("ManageSuccessionPlanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage User.
        /// </summary>
        public static string ManageUser {
            get {
                return ResourceManager.GetString("ManageUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manpower.
        /// </summary>
        public static string Manpower {
            get {
                return ResourceManager.GetString("Manpower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Home.
        /// </summary>
        public static string MyHome {
            get {
                return ResourceManager.GetString("MyHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Department Home.
        /// </summary>
        public static string MyOrganizationHome {
            get {
                return ResourceManager.GetString("MyOrganizationHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Directory.
        /// </summary>
        public static string OfficeDirectory {
            get {
                return ResourceManager.GetString("OfficeDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Hierarchy.
        /// </summary>
        public static string OrganizationHierarchy {
            get {
                return ResourceManager.GetString("OrganizationHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Home.
        /// </summary>
        public static string OrganizationHome {
            get {
                return ResourceManager.GetString("OrganizationHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OT/Deduction Approval.
        /// </summary>
        public static string OTDeductionApproval {
            get {
                return ResourceManager.GetString("OTDeductionApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Roll.
        /// </summary>
        public static string PayRoll {
            get {
                return ResourceManager.GetString("PayRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf.
        /// </summary>
        public static string Pdf {
            get {
                return ResourceManager.GetString("Pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string Performance {
            get {
                return ResourceManager.GetString("Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Settings.
        /// </summary>
        public static string PerformanceSettings {
            get {
                return ResourceManager.GetString("PerformanceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Salary Info.
        /// </summary>
        public static string PersonSalaryInfo {
            get {
                return ResourceManager.GetString("PersonSalaryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Hierarchy.
        /// </summary>
        public static string PositionHierarchy {
            get {
                return ResourceManager.GetString("PositionHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Management.
        /// </summary>
        public static string ProjectManagement {
            get {
                return ResourceManager.GetString("ProjectManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant Waiting List.
        /// </summary>
        public static string RestaurantWaitingList {
            get {
                return ResourceManager.GetString("RestaurantWaitingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roster Schedule.
        /// </summary>
        public static string RosterSchedule {
            get {
                return ResourceManager.GetString("RosterSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DashBoard.
        /// </summary>
        public static string SalesDashboard {
            get {
                return ResourceManager.GetString("SalesDashboard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DashBoard.
        /// </summary>
        public static string Cpm
        {
            get
            {
                return ResourceManager.GetString("Cpm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DashBoard.
        /// </summary>
        public static string CpmDashboard
        {
            get
            {
                return ResourceManager.GetString("CpmDashboard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        public static string SpsTraining {
            get {
                return ResourceManager.GetString("SpsTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succession Planning.
        /// </summary>
        public static string SuccessionPlanning {
            get {
                return ResourceManager.GetString("SuccessionPlanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succession Planning DashBoard.
        /// </summary>
        public static string SuccessionPlanningDashBoard {
            get {
                return ResourceManager.GetString("SuccessionPlanningDashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succession Planning Master.
        /// </summary>
        public static string SuccessionPlanningMaster {
            get {
                return ResourceManager.GetString("SuccessionPlanningMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Profile.
        /// </summary>
        public static string SwitchProfile {
            get {
                return ResourceManager.GetString("SwitchProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time And Attendance.
        /// </summary>
        public static string TimeAndAttendance {
            get {
                return ResourceManager.GetString("TimeAndAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time And Attendence.
        /// </summary>
        public static string TimeAndAttendence {
            get {
                return ResourceManager.GetString("TimeAndAttendence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workforce Structure.
        /// </summary>
        public static string WorkforceStructure {
            get {
                return ResourceManager.GetString("WorkforceStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worklist.
        /// </summary>
        public static string Worklist {
            get {
                return ResourceManager.GetString("Worklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worklist Settings.
        /// </summary>
        public static string WorklistSettings {
            get {
                return ResourceManager.GetString("WorklistSettings", resourceCulture);
            }
        }
    }
}
