//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ERP.Utility;
using System;
using System.Linq;

namespace ERP.Data.GraphModel
{
  
    public class HRS_RestaurantCustomerDetails : NodeBase
    {
        public string CustomerName { get; set; }
        public long OrganizationId { get; set; }
        public string MobileNo { get; set; }
    }

}
