//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Data.GraphModel
{
    public partial class HRS_City : NodeBase
    {
        public string Code { get; set; }
        public string Name { get; set; }
    }
    public class R_City_Country : RelationshipBase
    {

    }
    public partial class HRS_City_Log : HRS_City
    {
        public string CountryName { get; set; }
    }
}
