//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ERP.Utility;
using System;

namespace ERP.Data.GraphModel
{


    public partial class HRS_AssignmentMaster : NodeBase
    {
        public bool IsPrimaryAssignment { get; set; }
        public DateTime DateOfJoin { get; set; }
        public Nullable<DateTime> ProbationEndDate { get; set; }
        public Nullable<DateTime> NoticeStartDate { get; set; }
        public Nullable<DateTime> ActualTerminationDate { get; set; }
    }  
}


