//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;

namespace ERP.Data.GraphModel
{
    public partial class HRS_TicketDestination : NodeBase
    {
        public string Name { get; set; }
        public string NameLocal { get; set; }
    }
  
    public class R_TicketDestination_Country : RelationshipBase
    {

    }
}
