//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Data.GraphModel
{
    public partial class HRS_Sponsor : NodeBase
    {
        public string Code { get; set; }
        public string Name { get; set; }
    }

    public partial class HRS_Sponsor_Log : HRS_Sponsor
    {        
              
    }
}
