//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Data.Model
{
    public partial class HRS_ListOfValue : GeneralBase
    {
        public string LOVTypeCode { get; set; }
        public string Code { get; set; }

        public string Name { get; set; }
        public string NameLocal { get; set; }
        public string Description { get; set; }
        public string ParentCode { get; set; }
        //  public long? SequenceNo { get; set; }
        public string Groupcode { get; set; }

    }
}
