//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.UI.Web.Resources.Areas.Pay.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PayrollRunController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PayrollRunController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMS.UI.Web.Resources.Areas.Pay.Controllers.PayrollRunController", typeof(PayrollRunController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accural Date.
        /// </summary>
        public static string AccuralDate {
            get {
                return ResourceManager.GetString("AccuralDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EOS Accural.
        /// </summary>
        public static string EOSAccural {
            get {
                return ResourceManager.GetString("EOSAccural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight Ticket Accrual.
        /// </summary>
        public static string FlightTicketAccrual {
            get {
                return ResourceManager.GetString("FlightTicketAccrual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Accrual.
        /// </summary>
        public static string LoanAccrual {
            get {
                return ResourceManager.GetString("LoanAccrual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Accural.
        /// </summary>
        public static string ManageAccrual {
            get {
                return ResourceManager.GetString("ManageAccrual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sick Leave Accrual.
        /// </summary>
        public static string SickLeaveAccrual {
            get {
                return ResourceManager.GetString("SickLeaveAccrual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation Accrual.
        /// </summary>
        public static string VacationAccrual {
            get {
                return ResourceManager.GetString("VacationAccrual", resourceCulture);
            }
        }
    }
}
