//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synergy.App.WebUtility.Resources.Areas.BLS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BLSApplicationController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BLSApplicationController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Synergy.App.WebUtility.Resources.Areas.BLS.BLSApplicationController", typeof(BLSApplicationController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accomodation.
        /// </summary>
        public static string Accomodation {
            get {
                return ResourceManager.GetString("Accomodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1.
        /// </summary>
        public static string Address1 {
            get {
                return ResourceManager.GetString("Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        public static string Address2 {
            get {
                return ResourceManager.GetString("Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment or suite.
        /// </summary>
        public static string Apartmentorsuite {
            get {
                return ResourceManager.GetString("Apartmentorsuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant.
        /// </summary>
        public static string Applicant {
            get {
                return ResourceManager.GetString("Applicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant Details.
        /// </summary>
        public static string ApplicantDetails {
            get {
                return ResourceManager.GetString("ApplicantDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant Email.
        /// </summary>
        public static string ApplicantEmail {
            get {
                return ResourceManager.GetString("ApplicantEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLICANTS DETAILS.
        /// </summary>
        public static string APPLICANTSDETAILS {
            get {
                return ResourceManager.GetString("APPLICANTSDETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment book for.
        /// </summary>
        public static string Appointmentbookfor {
            get {
                return ResourceManager.GetString("Appointmentbookfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Category.
        /// </summary>
        public static string AppointmentCategory {
            get {
                return ResourceManager.GetString("AppointmentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Date.
        /// </summary>
        public static string AppointmentDate {
            get {
                return ResourceManager.GetString("AppointmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Details.
        /// </summary>
        public static string AppointmentDetails {
            get {
                return ResourceManager.GetString("AppointmentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment No.
        /// </summary>
        public static string AppointmentNo {
            get {
                return ResourceManager.GetString("AppointmentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Slot.
        /// </summary>
        public static string AppointmentSlot {
            get {
                return ResourceManager.GetString("AppointmentSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Status.
        /// </summary>
        public static string AppointmentStatus {
            get {
                return ResourceManager.GetString("AppointmentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Time Slot.
        /// </summary>
        public static string AppointmentTimeSlot {
            get {
                return ResourceManager.GetString("AppointmentTimeSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you applying as?.
        /// </summary>
        public static string Areyouapplyingas_ {
            get {
                return ResourceManager.GetString("Areyouapplyingas?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival Date.
        /// </summary>
        public static string ArrivalDate {
            get {
                return ResourceManager.GetString("ArrivalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border of Entry OR Transit Route.
        /// </summary>
        public static string BorderofEntryORTransitRoute {
            get {
                return ResourceManager.GetString("BorderofEntryORTransitRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Appointment.
        /// </summary>
        public static string CancelAppointment {
            get {
                return ResourceManager.GetString("CancelAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number.
        /// </summary>
        public static string ContactNumber {
            get {
                return ResourceManager.GetString("ContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of birth.
        /// </summary>
        public static string Countryofbirth {
            get {
                return ResourceManager.GetString("Countryofbirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Application.
        /// </summary>
        public static string CreateApplication {
            get {
                return ResourceManager.GetString("CreateApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        public static string CreditCard {
            get {
                return ResourceManager.GetString("CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Nationality.
        /// </summary>
        public static string CurrentNationality {
            get {
                return ResourceManager.GetString("CurrentNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string DateofBirth {
            get {
                return ResourceManager.GetString("DateofBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Issue.
        /// </summary>
        public static string DateofIssue {
            get {
                return ResourceManager.GetString("DateofIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure Date.
        /// </summary>
        public static string DepartureDate {
            get {
                return ResourceManager.GetString("DepartureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diplomat Passport.
        /// </summary>
        public static string DiplomatPassport {
            get {
                return ResourceManager.GetString("DiplomatPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divorced.
        /// </summary>
        public static string Divorced {
            get {
                return ResourceManager.GetString("Divorced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration of Issue.
        /// </summary>
        public static string DurationofIssue {
            get {
                return ResourceManager.GetString("DurationofIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration of Stay Number of days.
        /// </summary>
        public static string DurationofStayNumberofdays {
            get {
                return ResourceManager.GetString("DurationofStayNumberofdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        public static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Name.
        /// </summary>
        public static string FamilyName {
            get {
                return ResourceManager.GetString("FamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father&apos;s Full Name.
        /// </summary>
        public static string Father_sFullName {
            get {
                return ResourceManager.GetString("Father\'sFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Number.
        /// </summary>
        public static string FileNumber {
            get {
                return ResourceManager.GetString("FileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial means used during your stay.
        /// </summary>
        public static string Financialmeansusedduringyourstay {
            get {
                return ResourceManager.GetString("Financialmeansusedduringyourstay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Details.
        /// </summary>
        public static string GetDetails {
            get {
                return ResourceManager.GetString("GetDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Card Number.
        /// </summary>
        public static string GreenCardNumber {
            get {
                return ResourceManager.GetString("GreenCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSTIN.
        /// </summary>
        public static string GSTIN {
            get {
                return ResourceManager.GetString("GSTIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host(s).
        /// </summary>
        public static string Host_s_ {
            get {
                return ResourceManager.GetString("Host(s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host City / State.
        /// </summary>
        public static string HostCity_State {
            get {
                return ResourceManager.GetString("HostCity/State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Company.
        /// </summary>
        public static string HostCompany {
            get {
                return ResourceManager.GetString("HostCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many appointments.
        /// </summary>
        public static string Howmanyappointments {
            get {
                return ResourceManager.GetString("Howmanyappointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to provide my consent.
        /// </summary>
        public static string Iagreetoprovidemyconsen {
            get {
                return ResourceManager.GetString("Iagreetoprovidemyconsen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I disagree and don&apos;t give my consent.
        /// </summary>
        public static string Idisagreeanddon_tgivemyconsent {
            get {
                return ResourceManager.GetString("Idisagreeanddon\'tgivemyconsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual.
        /// </summary>
        public static string Individual {
            get {
                return ResourceManager.GetString("Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date.
        /// </summary>
        public static string IssueDate {
            get {
                return ResourceManager.GetString("IssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued By.
        /// </summary>
        public static string IssuedBy {
            get {
                return ResourceManager.GetString("IssuedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Place.
        /// </summary>
        public static string IssuePlace {
            get {
                return ResourceManager.GetString("IssuePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Validity.
        /// </summary>
        public static string LongValidity {
            get {
                return ResourceManager.GetString("LongValidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Status.
        /// </summary>
        public static string MaritalStatus {
            get {
                return ResourceManager.GetString("MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Married.
        /// </summary>
        public static string Married {
            get {
                return ResourceManager.GetString("Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean of Transport.
        /// </summary>
        public static string MeanofTransport {
            get {
                return ResourceManager.GetString("MeanofTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money.
        /// </summary>
        public static string Money {
            get {
                return ResourceManager.GetString("Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother&apos;s Full Name.
        /// </summary>
        public static string Mother_sFullName {
            get {
                return ResourceManager.GetString("Mother\'sFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Entries.
        /// </summary>
        public static string MultipleEntries {
            get {
                return ResourceManager.GetString("MultipleEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next step.
        /// </summary>
        public static string Nextstep {
            get {
                return ResourceManager.GetString("Nextstep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Of Counter.
        /// </summary>
        public static string NoOfCounter {
            get {
                return ResourceManager.GetString("NoOfCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Applicants.
        /// </summary>
        public static string NumberofApplicants {
            get {
                return ResourceManager.GetString("NumberofApplicants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Entries.
        /// </summary>
        public static string NumberofEntries {
            get {
                return ResourceManager.GetString("NumberofEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is optional service for additional charge. Kindly visit additional service page for more information..
        /// </summary>
        public static string Optionalservice {
            get {
                return ResourceManager.GetString("Optionalservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordinary Passport.
        /// </summary>
        public static string OrdinaryPassport {
            get {
                return ResourceManager.GetString("OrdinaryPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Nationality (Nationality of Birth).
        /// </summary>
        public static string OriginalNationality {
            get {
                return ResourceManager.GetString("OriginalNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAN Number.
        /// </summary>
        public static string PANNumber {
            get {
                return ResourceManager.GetString("PANNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Issue Country.
        /// </summary>
        public static string PassportIssueCountry {
            get {
                return ResourceManager.GetString("PassportIssueCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Number.
        /// </summary>
        public static string PassportNumber {
            get {
                return ResourceManager.GetString("PassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Type.
        /// </summary>
        public static string PassportType {
            get {
                return ResourceManager.GetString("PassportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pincode.
        /// </summary>
        public static string Pincode {
            get {
                return ResourceManager.GetString("Pincode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of birth.
        /// </summary>
        public static string Placeofbirth {
            get {
                return ResourceManager.GetString("Placeofbirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of Issue.
        /// </summary>
        public static string PlaceofIssue {
            get {
                return ResourceManager.GetString("PlaceofIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the requirement of the visa you are applying for before scheduling your appointments..
        /// </summary>
        public static string Pleasecheck {
            get {
                return ResourceManager.GetString("Pleasecheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Specify.
        /// </summary>
        public static string PleaseSpecify {
            get {
                return ResourceManager.GetString("PleaseSpecify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium Lounge.
        /// </summary>
        public static string PremiumLounge {
            get {
                return ResourceManager.GetString("PremiumLounge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Schengen Visa in the last 2 years.
        /// </summary>
        public static string PreviousSchengenVisainthelast2years {
            get {
                return ResourceManager.GetString("PreviousSchengenVisainthelast2years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printout.
        /// </summary>
        public static string Printout {
            get {
                return ResourceManager.GetString("Printout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Application.
        /// </summary>
        public static string ProcessApplication {
            get {
                return ResourceManager.GetString("ProcessApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession.
        /// </summary>
        public static string Profession {
            get {
                return ResourceManager.GetString("Profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose of Travel.
        /// </summary>
        public static string PurposeofTravel {
            get {
                return ResourceManager.GetString("PurposeofTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Verification Code.
        /// </summary>
        public static string RequestVerificationCode {
            get {
                return ResourceManager.GetString("RequestVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reschedule Appointment.
        /// </summary>
        public static string RescheduleAppointment {
            get {
                return ResourceManager.GetString("RescheduleAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend verification Code.
        /// </summary>
        public static string ResendVerificationCode {
            get {
                return ResourceManager.GetString("ResendVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your center.
        /// </summary>
        public static string Selectyourcenter {
            get {
                return ResourceManager.GetString("Selectyourcenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self.
        /// </summary>
        public static string Self {
            get {
                return ResourceManager.GetString("Self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separated.
        /// </summary>
        public static string Separated {
            get {
                return ResourceManager.GetString("Separated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Passport or equivalent.
        /// </summary>
        public static string ServicePassportorequivalent {
            get {
                return ResourceManager.GetString("ServicePassportorequivalent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Type.
        /// </summary>
        public static string ServiceType {
            get {
                return ResourceManager.GetString("ServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Validity.
        /// </summary>
        public static string ShortValidity {
            get {
                return ResourceManager.GetString("ShortValidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Entry.
        /// </summary>
        public static string SingleEntry {
            get {
                return ResourceManager.GetString("SingleEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot Category.
        /// </summary>
        public static string SlotCategory {
            get {
                return ResourceManager.GetString("SlotCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot Duration.
        /// </summary>
        public static string SlotDuration {
            get {
                return ResourceManager.GetString("SlotDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS.
        /// </summary>
        public static string SMS {
            get {
                return ResourceManager.GetString("SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Application.
        /// </summary>
        public static string SubmitApplication {
            get {
                return ResourceManager.GetString("SubmitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname At Birth.
        /// </summary>
        public static string SurnameAtBirth {
            get {
                return ResourceManager.GetString("SurnameAtBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Address in Morocco.
        /// </summary>
        public static string TemporaryAddressinMorocco {
            get {
                return ResourceManager.GetString("TemporaryAddressinMorocco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        public static string TermsofService {
            get {
                return ResourceManager.GetString("TermsofService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transit.
        /// </summary>
        public static string Transit {
            get {
                return ResourceManager.GetString("Transit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Agent.
        /// </summary>
        public static string TravelAgent {
            get {
                return ResourceManager.GetString("TravelAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Agent Name.
        /// </summary>
        public static string TravelAgentName {
            get {
                return ResourceManager.GetString("TravelAgentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Date.
        /// </summary>
        public static string TravelDate {
            get {
                return ResourceManager.GetString("TravelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel document for refugier.
        /// </summary>
        public static string Traveldocumentforrefugier {
            get {
                return ResourceManager.GetString("Traveldocumentforrefugier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Insurance.
        /// </summary>
        public static string TravelInsurance {
            get {
                return ResourceManager.GetString("TravelInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traveller Cheques.
        /// </summary>
        public static string TravellerCheques {
            get {
                return ResourceManager.GetString("TravellerCheques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Entries.
        /// </summary>
        public static string TwoEntries {
            get {
                return ResourceManager.GetString("TwoEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of travel document.
        /// </summary>
        public static string Typ_oftraveldocument {
            get {
                return ResourceManager.GetString("Typ oftraveldocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Visa.
        /// </summary>
        public static string TypeofVisa {
            get {
                return ResourceManager.GetString("TypeofVisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Until.
        /// </summary>
        public static string ValidUntil {
            get {
                return ResourceManager.GetString("ValidUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code.
        /// </summary>
        public static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Applicant.
        /// </summary>
        public static string VerifyApplicant {
            get {
                return ResourceManager.GetString("VerifyApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Appointment Form.
        /// </summary>
        public static string VisaAppointmentForm {
            get {
                return ResourceManager.GetString("VisaAppointmentForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Type.
        /// </summary>
        public static string VisaType {
            get {
                return ResourceManager.GetString("VisaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where are you applying from?.
        /// </summary>
        public static string Whereareyouapplyingfrom_ {
            get {
                return ResourceManager.GetString("Whereareyouapplyingfrom?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who is paying for your travel and your needs during your stay?.
        /// </summary>
        public static string Whoispaying {
            get {
                return ResourceManager.GetString("Whoispaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widow.
        /// </summary>
        public static string Widow {
            get {
                return ResourceManager.GetString("Widow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        public static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
    }
}
