//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Translation.Nts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Task {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Task() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERP.Translation.Nts.Task", typeof(Task).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sub Task.
        /// </summary>
        public static string AddSubTask {
            get {
                return ResourceManager.GetString("AddSubTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task Template.
        /// </summary>
        public static string AddTaskTemplate {
            get {
                return ResourceManager.GetString("AddTaskTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task canceled successfully.
        /// </summary>
        public static string AlertCancelSuccess {
            get {
                return ResourceManager.GetString("AlertCancelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task closed successfully.
        /// </summary>
        public static string AlertCloseSuccess {
            get {
                return ResourceManager.GetString("AlertCloseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task completed successfully.
        /// </summary>
        public static string AlertCompleteSuccess {
            get {
                return ResourceManager.GetString("AlertCompleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task drafted successfully.
        /// </summary>
        public static string AlertDraftSuccess {
            get {
                return ResourceManager.GetString("AlertDraftSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task rejected successfully.
        /// </summary>
        public static string AlertRejectSuccess {
            get {
                return ResourceManager.GetString("AlertRejectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task saved successfully.
        /// </summary>
        public static string AlertSaveSuccess {
            get {
                return ResourceManager.GetString("AlertSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task submitted successfully.
        /// </summary>
        public static string AlertSubmitSuccess {
            get {
                return ResourceManager.GetString("AlertSubmitSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Past Start Date.
        /// </summary>
        public static string AllowPastStartDate {
            get {
                return ResourceManager.GetString("AllowPastStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Completed.
        /// </summary>
        public static string AssignCompleted {
            get {
                return ResourceManager.GetString("AssignCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned By Query.
        /// </summary>
        public static string AssignedByQuery {
            get {
                return ResourceManager.GetString("AssignedByQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Query Type.
        /// </summary>
        public static string AssignedQueryType {
            get {
                return ResourceManager.GetString("AssignedQueryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignee.
        /// </summary>
        public static string AssignedTo {
            get {
                return ResourceManager.GetString("AssignedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign To Hierarchy.
        /// </summary>
        public static string AssignedToHierarchyId {
            get {
                return ResourceManager.GetString("AssignedToHierarchyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign To Hierarchy Level.
        /// </summary>
        public static string AssignedToHierarchyLevelNo {
            get {
                return ResourceManager.GetString("AssignedToHierarchyLevelNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned To Me.
        /// </summary>
        public static string AssignedToMe {
            get {
                return ResourceManager.GetString("AssignedToMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignee To.
        /// </summary>
        public static string AssignedUserUserName {
            get {
                return ResourceManager.GetString("AssignedUserUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignee To.
        /// </summary>
        public static string AssignedUserUserNameWithEmail {
            get {
                return ResourceManager.GetString("AssignedUserUserNameWithEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignee Display Name.
        /// </summary>
        public static string AssigneeDisplayName {
            get {
                return ResourceManager.GetString("AssigneeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Overdue.
        /// </summary>
        public static string AssignOverdue {
            get {
                return ResourceManager.GetString("AssignOverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Pending.
        /// </summary>
        public static string AssignPending {
            get {
                return ResourceManager.GetString("AssignPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign To Type.
        /// </summary>
        public static string AssignToType {
            get {
                return ResourceManager.GetString("AssignToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        public static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can View Service Reference.
        /// </summary>
        public static string CanViewServiceReference {
            get {
                return ResourceManager.GetString("CanViewServiceReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commented By.
        /// </summary>
        public static string CommentedByUserId {
            get {
                return ResourceManager.GetString("CommentedByUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CommentedByUserUserName {
            get {
                return ResourceManager.GetString("CommentedByUserUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed By User Id.
        /// </summary>
        public static string CompletedByUserId {
            get {
                return ResourceManager.GetString("CompletedByUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion Date.
        /// </summary>
        public static string CompletionDate {
            get {
                return ResourceManager.GetString("CompletionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Edit.
        /// </summary>
        public static string ConfirmEdit {
            get {
                return ResourceManager.GetString("ConfirmEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that edit will reassign the task to the assignee. Are you sure you want to continue?.
        /// </summary>
        public static string ConfirmEditMessage {
            get {
                return ResourceManager.GetString("ConfirmEditMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Type.
        /// </summary>
        public static string ContentType {
            get {
                return ResourceManager.GetString("ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Task.
        /// </summary>
        public static string CreateNewTask {
            get {
                return ResourceManager.GetString("CreateNewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Sub Task.
        /// </summary>
        public static string CreateSubTask {
            get {
                return ResourceManager.GetString("CreateSubTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Task.
        /// </summary>
        public static string CreateTask {
            get {
                return ResourceManager.GetString("CreateTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV FileIds.
        /// </summary>
        public static string CSVFileIds {
            get {
                return ResourceManager.GetString("CSVFileIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Mode.
        /// </summary>
        public static string DisplayMode {
            get {
                return ResourceManager.GetString("DisplayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Task Auto Complete.
        /// </summary>
        public static string EnableTaskAutoComplete {
            get {
                return ResourceManager.GetString("EnableTaskAutoComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Name.
        /// </summary>
        public static string EventName {
            get {
                return ResourceManager.GetString("EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Extension.
        /// </summary>
        public static string FileExtension {
            get {
                return ResourceManager.GetString("FileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Upload.
        /// </summary>
        public static string FileId {
            get {
                return ResourceManager.GetString("FileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Type.
        /// </summary>
        public static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatted Created Date.
        /// </summary>
        public static string FormattedCreatedDate {
            get {
                return ResourceManager.GetString("FormattedCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HideIfDraft.
        /// </summary>
        public static string HideIfDraft {
            get {
                return ResourceManager.GetString("HideIfDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Assigned In Template.
        /// </summary>
        public static string IsAssignedInTemplate {
            get {
                return ResourceManager.GetString("IsAssignedInTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Confidential.
        /// </summary>
        public static string IsConfidential {
            get {
                return ResourceManager.GetString("IsConfidential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsHiiden.
        /// </summary>
        public static string IsHiiden {
            get {
                return ResourceManager.GetString("IsHiiden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is In Physical Path.
        /// </summary>
        public static string IsInPhysicalPath {
            get {
                return ResourceManager.GetString("IsInPhysicalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsLatestVersion.
        /// </summary>
        public static string IsLatestVersion {
            get {
                return ResourceManager.GetString("IsLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Lock Visible.
        /// </summary>
        public static string IsLockVisible {
            get {
                return ResourceManager.GetString("IsLockVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Notification Sent.
        /// </summary>
        public static string IsNotificationSent {
            get {
                return ResourceManager.GetString("IsNotificationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Owner.
        /// </summary>
        public static string IsOwner {
            get {
                return ResourceManager.GetString("IsOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Release Visible.
        /// </summary>
        public static string IsReleaseVisible {
            get {
                return ResourceManager.GetString("IsReleaseVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Task Auto Complete.
        /// </summary>
        public static string IsTaskAutoComplete {
            get {
                return ResourceManager.GetString("IsTaskAutoComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Task Auto Complete If Same Assignee.
        /// </summary>
        public static string IsTaskAutoCompleteIfSameAssignee {
            get {
                return ResourceManager.GetString("IsTaskAutoCompleteIfSameAssignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Status.
        /// </summary>
        public static string LockStatus {
            get {
                return ResourceManager.GetString("LockStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem in Locking the Task, Please contact administrator.
        /// </summary>
        public static string LockTaskException {
            get {
                return ResourceManager.GetString("LockTaskException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Task Id.
        /// </summary>
        public static string LogTaskId {
            get {
                return ResourceManager.GetString("LogTaskId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile View.
        /// </summary>
        public static string MobileView {
            get {
                return ResourceManager.GetString("MobileView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Title.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Template Id.
        /// </summary>
        public static string NotificationTemplateId {
            get {
                return ResourceManager.GetString("NotificationTemplateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nts Classification.
        /// </summary>
        public static string NtsClassification {
            get {
                return ResourceManager.GetString("NtsClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nts Type.
        /// </summary>
        public static string NtsType {
            get {
                return ResourceManager.GetString("NtsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Owner.
        /// </summary>
        public static string OwnerDisplayName {
            get {
                return ResourceManager.GetString("OwnerDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string OwnerName {
            get {
                return ResourceManager.GetString("OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner User Email.
        /// </summary>
        public static string OwnerUserEmail {
            get {
                return ResourceManager.GetString("OwnerUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Owner.
        /// </summary>
        public static string OwnerUserId {
            get {
                return ResourceManager.GetString("OwnerUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner User Password.
        /// </summary>
        public static string OwnerUserPassword {
            get {
                return ResourceManager.GetString("OwnerUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Owner.
        /// </summary>
        public static string OwnerUserUserName {
            get {
                return ResourceManager.GetString("OwnerUserUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Task.
        /// </summary>
        public static string page_manage_title {
            get {
                return ResourceManager.GetString("page_manage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Task.
        /// </summary>
        public static string PageTitleIndex {
            get {
                return ResourceManager.GetString("PageTitleIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task List.
        /// </summary>
        public static string PageTitleTaskList {
            get {
                return ResourceManager.GetString("PageTitleTaskList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Filter With Task .
        /// </summary>
        public static string PageTitleTaskListMsg {
            get {
                return ResourceManager.GetString("PageTitleTaskListMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string ParentComment {
            get {
                return ResourceManager.GetString("ParentComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Task Comment Id.
        /// </summary>
        public static string ParentTaskCommentId {
            get {
                return ResourceManager.GetString("ParentTaskCommentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParentTaskId.
        /// </summary>
        public static string ParentTaskId {
            get {
                return ResourceManager.GetString("ParentTaskId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Template Category Id.
        /// </summary>
        public static string ParentTemplateCategoryId {
            get {
                return ResourceManager.GetString("ParentTemplateCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Comment.
        /// </summary>
        public static string PostComment {
            get {
                return ResourceManager.GetString("PostComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Message.
        /// </summary>
        public static string PostMessage {
            get {
                return ResourceManager.GetString("PostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating Type.
        /// </summary>
        public static string RatingTemplateId {
            get {
                return ResourceManager.GetString("RatingTemplateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating Type.
        /// </summary>
        public static string RatingTypeCode {
            get {
                return ResourceManager.GetString("RatingTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating Type.
        /// </summary>
        public static string RatingTypeName {
            get {
                return ResourceManager.GetString("RatingTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected By User Id.
        /// </summary>
        public static string RejectedByUserId {
            get {
                return ResourceManager.GetString("RejectedByUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem in Locking the Task, Please contact administrator.
        /// </summary>
        public static string ReleaseTaskException {
            get {
                return ResourceManager.GetString("ReleaseTaskException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder Date.
        /// </summary>
        public static string ReminderDate {
            get {
                return ResourceManager.GetString("ReminderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder Description.
        /// </summary>
        public static string ReminderDescription {
            get {
                return ResourceManager.GetString("ReminderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Completed.
        /// </summary>
        public static string RequestCompleted {
            get {
                return ResourceManager.GetString("RequestCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Draft .
        /// </summary>
        public static string RequestDraft {
            get {
                return ResourceManager.GetString("RequestDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested By Me.
        /// </summary>
        public static string RequestedByMe {
            get {
                return ResourceManager.GetString("RequestedByMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Overdue.
        /// </summary>
        public static string RequestOverdue {
            get {
                return ResourceManager.GetString("RequestOverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Pending.
        /// </summary>
        public static string RequestPending {
            get {
                return ResourceManager.GetString("RequestPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned To.
        /// </summary>
        public static string ReturnedTo {
            get {
                return ResourceManager.GetString("ReturnedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Description.
        /// </summary>
        public static string ScheduleDescription {
            get {
                return ResourceManager.GetString("ScheduleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Criteria.
        /// </summary>
        public static string SearchCriteria {
            get {
                return ResourceManager.GetString("SearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected File.
        /// </summary>
        public static string SelectedFile {
            get {
                return ResourceManager.GetString("SelectedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Id.
        /// </summary>
        public static string ServiceId {
            get {
                return ResourceManager.GetString("ServiceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name.
        /// </summary>
        public static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service No.
        /// </summary>
        public static string ServiceNo {
            get {
                return ResourceManager.GetString("ServiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Owner.
        /// </summary>
        public static string ServiceOwner {
            get {
                return ResourceManager.GetString("ServiceOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Owner Act As Step Task Assignee.
        /// </summary>
        public static string ServiceOwnerActAsStepTaskAssignee {
            get {
                return ResourceManager.GetString("ServiceOwnerActAsStepTaskAssignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Owner User Id.
        /// </summary>
        public static string ServiceOwnerUserId {
            get {
                return ResourceManager.GetString("ServiceOwnerUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceReferenceId.
        /// </summary>
        public static string ServiceReferenceId {
            get {
                return ResourceManager.GetString("ServiceReferenceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Reference Text.
        /// </summary>
        public static string ServiceReferenceText {
            get {
                return ResourceManager.GetString("ServiceReferenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceTaskTemplateId.
        /// </summary>
        public static string ServiceTaskTemplateId {
            get {
                return ResourceManager.GetString("ServiceTaskTemplateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Task Type.
        /// </summary>
        public static string ServiceTaskType {
            get {
                return ResourceManager.GetString("ServiceTaskType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Task Version Id.
        /// </summary>
        public static string ServiceTaskVersionId {
            get {
                return ResourceManager.GetString("ServiceTaskVersionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Template Id.
        /// </summary>
        public static string ServiceTemplateId {
            get {
                return ResourceManager.GetString("ServiceTemplateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Template Name.
        /// </summary>
        public static string ServiceTemplateName {
            get {
                return ResourceManager.GetString("ServiceTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service VersionId.
        /// </summary>
        public static string ServiceVersionId {
            get {
                return ResourceManager.GetString("ServiceVersionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared By Me.
        /// </summary>
        public static string SharedByMe {
            get {
                return ResourceManager.GetString("SharedByMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared To.
        /// </summary>
        public static string SharedTo {
            get {
                return ResourceManager.GetString("SharedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared To User Name.
        /// </summary>
        public static string SharedToUserName {
            get {
                return ResourceManager.GetString("SharedToUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared To Type.
        /// </summary>
        public static string SharedType {
            get {
                return ResourceManager.GetString("SharedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared With Me.
        /// </summary>
        public static string SharedWithMe {
            get {
                return ResourceManager.GetString("SharedWithMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLA(In Days).
        /// </summary>
        public static string SLA {
            get {
                return ResourceManager.GetString("SLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLA Calculation Mode.
        /// </summary>
        public static string SLACalculationMode {
            get {
                return ResourceManager.GetString("SLACalculationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Step Task.
        /// </summary>
        public static string StepTaskAddButtonText {
            get {
                return ResourceManager.GetString("StepTaskAddButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select Task Type--.
        /// </summary>
        public static string StepTaskCreationOptionalLabel {
            get {
                return ResourceManager.GetString("StepTaskCreationOptionalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Task.
        /// </summary>
        public static string SubTask {
            get {
                return ResourceManager.GetString("SubTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more approval tasks are not configured to any assignee. Please contact administrator.
        /// </summary>
        public static string TaskConfigureMessage {
            get {
                return ResourceManager.GetString("TaskConfigureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Field Value Id.
        /// </summary>
        public static string TaskFieldValueId {
            get {
                return ResourceManager.GetString("TaskFieldValueId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Field Value Version Id.
        /// </summary>
        public static string TaskFieldValueVersionId {
            get {
                return ResourceManager.GetString("TaskFieldValueVersionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Id.
        /// </summary>
        public static string TaskId {
            get {
                return ResourceManager.GetString("TaskId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Name.
        /// </summary>
        public static string TaskName {
            get {
                return ResourceManager.GetString("TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task No.
        /// </summary>
        public static string TaskNo {
            get {
                return ResourceManager.GetString("TaskNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Shared Id.
        /// </summary>
        public static string TaskSharedId {
            get {
                return ResourceManager.GetString("TaskSharedId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Shared List.
        /// </summary>
        public static string TaskSharedList {
            get {
                return ResourceManager.GetString("TaskSharedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Status.
        /// </summary>
        public static string TaskStatusCode {
            get {
                return ResourceManager.GetString("TaskStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Status.
        /// </summary>
        public static string TaskStatusName {
            get {
                return ResourceManager.GetString("TaskStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Template Name.
        /// </summary>
        public static string TaskTemplateId {
            get {
                return ResourceManager.GetString("TaskTemplateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Template Name.
        /// </summary>
        public static string TaskTemplateName {
            get {
                return ResourceManager.GetString("TaskTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Version Id.
        /// </summary>
        public static string TaskVersionId {
            get {
                return ResourceManager.GetString("TaskVersionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Id.
        /// </summary>
        public static string TeamId {
            get {
                return ResourceManager.GetString("TeamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamName.
        /// </summary>
        public static string TeamName {
            get {
                return ResourceManager.GetString("TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Category.
        /// </summary>
        public static string TemplateCategoryId {
            get {
                return ResourceManager.GetString("TemplateCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Field Id.
        /// </summary>
        public static string TemplateFieldId {
            get {
                return ResourceManager.GetString("TemplateFieldId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Template.
        /// </summary>
        public static string TemplateId {
            get {
                return ResourceManager.GetString("TemplateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggerd By Template.
        /// </summary>
        public static string TriggeredByTemplateId {
            get {
                return ResourceManager.GetString("TriggeredByTemplateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggerd By Template.
        /// </summary>
        public static string TriggeredByTemplateName {
            get {
                return ResourceManager.GetString("TriggeredByTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
