//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Translation.Clk {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Clk {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Clk() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERP.Translation.Clk.Clk", typeof(Clk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Log.
        /// </summary>
        public static string AccessLog {
            get {
                return ResourceManager.GetString("AccessLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biometric Id.
        /// </summary>
        public static string BiometricId {
            get {
                return ResourceManager.GetString("BiometricId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock Server.
        /// </summary>
        public static string ClockServer {
            get {
                return ResourceManager.GetString("ClockServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock Server Setting.
        /// </summary>
        public static string ClockServerSetting {
            get {
                return ResourceManager.GetString("ClockServerSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Type.
        /// </summary>
        public static string CommunicationType {
            get {
                return ResourceManager.GetString("CommunicationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct UserInfo.
        /// </summary>
        public static string CorrectUserInfo {
            get {
                return ResourceManager.GetString("CorrectUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create UserInfo.
        /// </summary>
        public static string CreateUserInfo {
            get {
                return ResourceManager.GetString("CreateUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay In Execution.
        /// </summary>
        public static string DelayInExecution {
            get {
                return ResourceManager.GetString("DelayInExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Data.
        /// </summary>
        public static string DeviceData {
            get {
                return ResourceManager.GetString("DeviceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string DeviceId {
            get {
                return ResourceManager.GetString("DeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Ip Address.
        /// </summary>
        public static string DeviceIpAddress {
            get {
                return ResourceManager.GetString("DeviceIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Machine No.
        /// </summary>
        public static string DeviceMachineNo {
            get {
                return ResourceManager.GetString("DeviceMachineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Name.
        /// </summary>
        public static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Port No.
        /// </summary>
        public static string DevicePortNo {
            get {
                return ResourceManager.GetString("DevicePortNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Punching Type.
        /// </summary>
        public static string DevicePunchingType {
            get {
                return ResourceManager.GetString("DevicePunchingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Serial No.
        /// </summary>
        public static string DeviceSerialNo {
            get {
                return ResourceManager.GetString("DeviceSerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Error Notification.
        /// </summary>
        public static string EnableErrorNotification {
            get {
                return ResourceManager.GetString("EnableErrorNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Manual Execution.
        /// </summary>
        public static string EnableManualExecution {
            get {
                return ResourceManager.GetString("EnableManualExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution End Date.
        /// </summary>
        public static string ExecutionEndDate {
            get {
                return ResourceManager.GetString("ExecutionEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Start Date.
        /// </summary>
        public static string ExecutionStartDate {
            get {
                return ResourceManager.GetString("ExecutionStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Status.
        /// </summary>
        public static string ExecutionStatus {
            get {
                return ResourceManager.GetString("ExecutionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finger Index.
        /// </summary>
        public static string FingerIndex {
            get {
                return ResourceManager.GetString("FingerIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idenification Image.
        /// </summary>
        public static string IdenificationImageBase64 {
            get {
                return ResourceManager.GetString("IdenificationImageBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Flag.
        /// </summary>
        public static string IFlag {
            get {
                return ResourceManager.GetString("IFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Schedule End Time.
        /// </summary>
        public static string LastScheduleEndTime {
            get {
                return ResourceManager.GetString("LastScheduleEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Schedule Start Time.
        /// </summary>
        public static string LastScheduleStartTime {
            get {
                return ResourceManager.GetString("LastScheduleStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Schedule Status.
        /// </summary>
        public static string LastScheduleStatus {
            get {
                return ResourceManager.GetString("LastScheduleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Successful Process Time.
        /// </summary>
        public static string LastSuccessfulProcessTime {
            get {
                return ResourceManager.GetString("LastSuccessfulProcessTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine No.
        /// </summary>
        public static string MachineNo {
            get {
                return ResourceManager.GetString("MachineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificiation Recipient.
        /// </summary>
        public static string NotificiationRecipient {
            get {
                return ResourceManager.GetString("NotificiationRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Log.
        /// </summary>
        public static string PageAccessLogTitle {
            get {
                return ResourceManager.GetString("PageAccessLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct Device.
        /// </summary>
        public static string PageCorrectDeviceTitle {
            get {
                return ResourceManager.GetString("PageCorrectDeviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct AccessLog.
        /// </summary>
        public static string PageCorrectLogTitle {
            get {
                return ResourceManager.GetString("PageCorrectLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct Product.
        /// </summary>
        public static string PageCorrectProductTitle {
            get {
                return ResourceManager.GetString("PageCorrectProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct Scheduler.
        /// </summary>
        public static string PageCorrectSchedulerTitle {
            get {
                return ResourceManager.GetString("PageCorrectSchedulerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct TimeZone.
        /// </summary>
        public static string PageCorrectTimeZoneTitle {
            get {
                return ResourceManager.GetString("PageCorrectTimeZoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct UserInfo.
        /// </summary>
        public static string PageCorrectUserInfoTitle {
            get {
                return ResourceManager.GetString("PageCorrectUserInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Device.
        /// </summary>
        public static string PageCreateDeviceTitle {
            get {
                return ResourceManager.GetString("PageCreateDeviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create AccessLog.
        /// </summary>
        public static string PageCreateLogTitle {
            get {
                return ResourceManager.GetString("PageCreateLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Product.
        /// </summary>
        public static string PageCreateProductTitle {
            get {
                return ResourceManager.GetString("PageCreateProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Scheduler.
        /// </summary>
        public static string PageCreateSchedulerTitle {
            get {
                return ResourceManager.GetString("PageCreateSchedulerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create TimeZone.
        /// </summary>
        public static string PageCreateTimeZoneTitle {
            get {
                return ResourceManager.GetString("PageCreateTimeZoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create UserInfo.
        /// </summary>
        public static string PageCreateUserInfoTitle {
            get {
                return ResourceManager.GetString("PageCreateUserInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Device.
        /// </summary>
        public static string PageDeleteDeviceTitle {
            get {
                return ResourceManager.GetString("PageDeleteDeviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete AccessLog.
        /// </summary>
        public static string PageDeleteLogTitle {
            get {
                return ResourceManager.GetString("PageDeleteLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Product.
        /// </summary>
        public static string PageDeleteProductTitle {
            get {
                return ResourceManager.GetString("PageDeleteProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Scheduler.
        /// </summary>
        public static string PageDeleteSchedulerTitle {
            get {
                return ResourceManager.GetString("PageDeleteSchedulerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete TimeZone.
        /// </summary>
        public static string PageDeleteTimeZoneTitle {
            get {
                return ResourceManager.GetString("PageDeleteTimeZoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete UserInfo.
        /// </summary>
        public static string PageDeleteUserInfoTitle {
            get {
                return ResourceManager.GetString("PageDeleteUserInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Device.
        /// </summary>
        public static string PageManageDeviceTitle {
            get {
                return ResourceManager.GetString("PageManageDeviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Param 1.
        /// </summary>
        public static string Param1 {
            get {
                return ResourceManager.GetString("Param1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Param 10.
        /// </summary>
        public static string Param10 {
            get {
                return ResourceManager.GetString("Param10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Param 2.
        /// </summary>
        public static string Param2 {
            get {
                return ResourceManager.GetString("Param2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Param 3.
        /// </summary>
        public static string Param3 {
            get {
                return ResourceManager.GetString("Param3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Param 4.
        /// </summary>
        public static string Param4 {
            get {
                return ResourceManager.GetString("Param4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Param 5.
        /// </summary>
        public static string Param5 {
            get {
                return ResourceManager.GetString("Param5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Param 6.
        /// </summary>
        public static string Param6 {
            get {
                return ResourceManager.GetString("Param6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Param 7.
        /// </summary>
        public static string Param7 {
            get {
                return ResourceManager.GetString("Param7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Param 8.
        /// </summary>
        public static string Param8 {
            get {
                return ResourceManager.GetString("Param8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Param 9.
        /// </summary>
        public static string Param9 {
            get {
                return ResourceManager.GetString("Param9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string PersonFullName {
            get {
                return ResourceManager.GetString("PersonFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Id.
        /// </summary>
        public static string PersonId {
            get {
                return ResourceManager.GetString("PersonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port No.
        /// </summary>
        public static string PortNo {
            get {
                return ResourceManager.GetString("PortNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privilege.
        /// </summary>
        public static string Privelage {
            get {
                return ResourceManager.GetString("Privelage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string ProductId {
            get {
                return ResourceManager.GetString("ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punching Time.
        /// </summary>
        public static string PunchingTime {
            get {
                return ResourceManager.GetString("PunchingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punching Type.
        /// </summary>
        public static string PunchingType {
            get {
                return ResourceManager.GetString("PunchingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Id.
        /// </summary>
        public static string ScheduleId {
            get {
                return ResourceManager.GetString("ScheduleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Order.
        /// </summary>
        public static string ScheduleOrder {
            get {
                return ResourceManager.GetString("ScheduleOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler.
        /// </summary>
        public static string Scheduler {
            get {
                return ResourceManager.GetString("Scheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Action.
        /// </summary>
        public static string SchedulerAction {
            get {
                return ResourceManager.GetString("SchedulerAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Recurrence.
        /// </summary>
        public static string ScheduleRecur {
            get {
                return ResourceManager.GetString("ScheduleRecur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Time.
        /// </summary>
        public static string ScheduleTime {
            get {
                return ResourceManager.GetString("ScheduleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Type.
        /// </summary>
        public static string ScheduleType {
            get {
                return ResourceManager.GetString("ScheduleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial No.
        /// </summary>
        public static string SerialNo {
            get {
                return ResourceManager.GetString("SerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iqamah No.
        /// </summary>
        public static string SponsorshipNo {
            get {
                return ResourceManager.GetString("SponsorshipNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful Schedule Time.
        /// </summary>
        public static string SuccessfulScheduleTime {
            get {
                return ResourceManager.GetString("SuccessfulScheduleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Zone.
        /// </summary>
        public static string TimeZoneId {
            get {
                return ResourceManager.GetString("TimeZoneId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Info.
        /// </summary>
        public static string UserInfo {
            get {
                return ResourceManager.GetString("UserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Info Id.
        /// </summary>
        public static string UserInfoId {
            get {
                return ResourceManager.GetString("UserInfoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utc OffSet.
        /// </summary>
        public static string UtcOffSet {
            get {
                return ResourceManager.GetString("UtcOffSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
