FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /api
COPY *.sln .
COPY synergyapi.slnf .
COPY NuGet.Config .
COPY Synergy.App.Web/LocalDependencies/ ./Synergy.App.Web/LocalDependencies/
COPY Synergy.App.Business/*.csproj ./Synergy.App.Business/
COPY Synergy.App.Common/*.csproj ./Synergy.App.Common/
COPY Synergy.App.DataModel/*.csproj ./Synergy.App.DataModel/
COPY Synergy.App.Repository/*.csproj ./Synergy.App.Repository/
COPY Synergy.App.Repository/MigrationScript/ ./MigrationScript/
COPY Synergy.App.ViewModel/*.csproj ./Synergy.App.ViewModel/
COPY Synergy.App.Api/*.csproj ./Synergy.App.Api/
RUN dotnet restore synergyapi.slnf

COPY . .

WORKDIR /api/Synergy.App.ViewModel
RUN dotnet publish -c Release -o /out --no-restore

WORKDIR /api/Synergy.App.Repository
RUN dotnet publish -c Release -o /out --no-restore

WORKDIR /api/Synergy.App.DataModel
RUN dotnet publish -c Release -o /out --no-restore

WORKDIR /api/Synergy.App.Common
RUN dotnet publish -c Release -o /out --no-restore

WORKDIR /api/Synergy.App.Business
RUN dotnet publish -c Release -o /out --no-restore

WORKDIR /api/Synergy.App.Api
RUN dotnet publish -c Release -o /out --no-restore

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS runtime

#RUN apt-get update; apt-get install -y ttf-mscorefonts-installer fontconfig
RUN apt-get update && apt-get install -y libreoffice
RUN apt-get update && apt-get install -y poppler-utils

WORKDIR /api 

COPY --from=build /out ./

ENV ASPNETCORE_ENVIRONMENT Production
ENV ASPNETCORE_URLS http://*:3000
ENTRYPOINT ["dotnet", "Synergy.App.Api.dll"]

