FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build

#ENV http_proxy http://192.168.75.3:8080
#ENV https_proxy http://192.168.75.3:8080


WORKDIR /app
COPY *.sln .
COPY synergyweb.slnf .
COPY NuGet.Config .
COPY Synergy.App.Web/*.csproj ./Synergy.App.Web/
COPY Synergy.App.Web/LocalDependencies/ ./Synergy.App.Web/LocalDependencies/
COPY Synergy.App.Business/*.csproj ./Synergy.App.Business/
COPY Synergy.App.Common/*.csproj ./Synergy.App.Common/
COPY Synergy.App.Core/*.csproj ./Synergy.App.Core/
COPY Synergy.App.DataModel/*.csproj ./Synergy.App.DataModel/
COPY Synergy.App.Repository/*.csproj ./Synergy.App.Repository/
COPY Synergy.App.Repository/MigrationScript/ ./MigrationScript/
COPY Synergy.App.ViewModel/*.csproj ./Synergy.App.ViewModel/
COPY Synergy.App.WebUtility/*.csproj ./Synergy.App.WebUtility/
COPY Synergy.App.Dms/*.csproj ./Synergy.App.Dms/
COPY Synergy.App.Hrms/*.csproj ./Synergy.App.Hrms/
COPY Synergy.App.Inventory/*.csproj ./Synergy.App.Inventory/
COPY Synergy.App.Others/*.csproj ./Synergy.App.Others/
COPY Synergy.App.PerformanceManagement/*.csproj ./Synergy.App.PerformanceManagement/
COPY Synergy.App.ProjectManagement/*.csproj ./Synergy.App.ProjectManagement/
COPY Synergy.App.Recruitment/*.csproj ./Synergy.App.Recruitment/
COPY Synergy.App.SmartCity/*.csproj ./Synergy.App.SmartCity/
COPY Synergy.App.Website/*.csproj ./Synergy.App.Website/
COPY Synergy.App.Emirates/*.csproj ./Synergy.App.Emirates/
COPY Synergy.App.BLS/*.csproj ./Synergy.App.BLS/
RUN dotnet restore synergyweb.slnf

COPY . .

WORKDIR /app/Synergy.App.ViewModel
RUN dotnet publish -c Release -o /out --no-restore

WORKDIR /app/Synergy.App.Repository
RUN dotnet publish -c Release -o /out --no-restore

WORKDIR /app/Synergy.App.DataModel
RUN dotnet publish -c Release -o /out --no-restore

WORKDIR /app/Synergy.App.Common
RUN dotnet publish -c Release -o /out --no-restore

WORKDIR /app/Synergy.App.Business
RUN dotnet publish -c Release -o /out --no-restore

WORKDIR /app/Synergy.App.Core
RUN dotnet publish -c Release -o /out --no-restore

WORKDIR /app/Synergy.App.WebUtility
RUN dotnet publish -c Release -o /out --no-restore

WORKDIR /app/Synergy.App.Dms
RUN dotnet publish -c Release -o /out --no-restore

WORKDIR /app/Synergy.App.Hrms
RUN dotnet publish -c Release -o /out --no-restore

WORKDIR /app/Synergy.App.Inventory
RUN dotnet publish -c Release -o /out --no-restore

WORKDIR /app/Synergy.App.Others
RUN dotnet publish -c Release -o /out --no-restore

WORKDIR /app/Synergy.App.PerformanceManagement
RUN dotnet publish -c Release -o /out --no-restore

WORKDIR /app/Synergy.App.ProjectManagement
RUN dotnet publish -c Release -o /out --no-restore

WORKDIR /app/Synergy.App.Recruitment
RUN dotnet publish -c Release -o /out --no-restore

WORKDIR /app/Synergy.App.SmartCity
RUN dotnet publish -c Release -o /out --no-restore

WORKDIR /app/Synergy.App.Website
RUN dotnet publish -c Release -o /out --no-restore

WORKDIR /app/Synergy.App.Web
RUN dotnet publish -c Release -o /out --no-restore

WORKDIR /app/Synergy.App.Emirates
RUN dotnet publish -c Release -o /out --no-restore

WORKDIR /app/Synergy.App.BLS
RUN dotnet publish -c Release -o /out --no-restore

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS runtime

#ENV http_proxy http://192.168.75.3:8080
#ENV https_proxy http://192.168.75.3:8080

RUN apt-get update \ 
    && apt-get install -y --allow-unauthenticated \ 
        libc6-dev \ 
        libgdiplus \ 
        libx11-dev \ 
    && rm -rf /var/lib/apt/lists/*

RUN sed -i'.bak' 's/$/ contrib/' /etc/apt/sources.list
RUN apt-get update; apt-get install -y ttf-mscorefonts-installer fontconfig
#RUN apt-get update && apt-get install -y libreoffice

WORKDIR /app 

COPY --from=build /out ./

ENV ASPNETCORE_ENVIRONMENT Production
ENV ASPNETCORE_URLS http://*:5000
ENTRYPOINT ["dotnet", "Synergy.App.Web.dll"]