//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ERP.Utility;
using System;
using System.Linq;

namespace ERP.Data.GraphModel
{
    public partial class GEN_FileSnapshot : NodeBase
    {        
        public string FileName { get; set; }
        public string FileExtension { get; set; }
        public string ContentType { get; set; }
        public long ContentLength { get; set; }
        public string ContentBase64 { get; set; }
        public string Path { get; set; }
        public AttachmentTypeEnum? AttachmentType { get; set; }
        public long? LinkId { get; set; }
        public bool IsInPhysicalPath { get; set; }
        public string AttachmentDescription { get; set; }
    }
    public class R_FileSnapshot_File : RelationshipBase
    {

    }
}
