//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using ERP.Utility;
using System;
using System.Linq;

namespace ERP.Data.GraphModel
{
    public partial class GEN_Attachment : NodeBase
    {
        public string Name { get; set; }
        public long VersionNo { get; set; }
        public bool IsLatestVersion { get; set; }
        public long FileId { get; set; }
        public string Description { get; set; }

        public DateTime? DateOfIssue { get; set; }
        public DateTime? DateOfExpiry { get; set; }
        public string DocumentNo { get; set; }
        public string ApprovedAuthority { get; set; }
        public AttachmentTypeEnum? AttachmentType { get; set; }

    }



    public class R_Attachment_Reference : RelationshipBase
    {
        public ReferenceTypeEnum? ReferenceTypeCode { get; set; }
    }

}
