//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace ERP.Data.GraphModel
{

  
    public partial class GEN_DatedSequence : NodeBase
    {
        public string Name { get; set; }
        public string CompanyCode { get; set; }
        public string OrganizationCode { get; set; }
        public DateTime ForDate { get; set; }
        public long NextId { get; set; }
    }
}
