//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Data.GraphModel
{ 
    public partial class GEN_ListOfValue : NodeBase
    {        
        //public string LOVTypeCode { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string NameLocal { get; set; }
        public string Description { get; set; }
        //public string ParentCode { get; set; }
        public string Groupcode { get; set; }
        public bool? IsUserListOfValue { get; set; }
        public decimal? SequenceNo { get; set; }
    }
    public class R_ListOfValue_ListOfValueType : RelationshipBase
    {

    }
    public class R_ListOfValue_Parent : RelationshipBase
    {

    }
}
