version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: synergy
      MONGO_INITDB_ROOT_PASSWORD: Synergywelcome1
    ports:
      - 7474:27017
    volumes:
     - ./mongod.conf:/etc/mongod.conf
     - type: volume
       source: data
       target: /data/db

volumes:
  data:

networks:
  default:
    external:
      name: cmssynergy_default